// Run with node tests/communications.cjs. Uses Node's in-memory SQLite and real route handlers.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite'),{createRequire}=require('node:module');
const root=path.resolve(__dirname,'..'),ts=require('typescript'),out=fs.mkdtempSync(path.join(os.tmpdir(),'hb-communications-'));fs.symlinkSync(root+'/node_modules',out+'/node_modules','dir');
for(const f of ['lib/communications.ts','lib/board.ts','lib/file-validation.ts','app/api/board/route.ts','lib/moderation.ts','lib/admin-auth.ts','app/api/community/route.ts','app/api/attachments/route.ts','app/api/school-auth/route.ts']){const dest=out+'/'+f.replace(/\.ts$/,'.js');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,ts.transpileModule(fs.readFileSync(root+'/'+f,'utf8').replaceAll("'@/",`'${out}/`),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)}
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync(root+'/drizzle/'+f,'utf8'));
const storage=new Map();const database={prepare(query){let values=[];return {bind(...v){values=v;return this},async first(){return sql.prepare(query).get(...values)||null},async all(){return {results:sql.prepare(query).all(...values)}},async run(){const r=sql.prepare(query).run(...values);return {meta:{changes:Number(r.changes)}}}}},async batch(list){sql.exec('BEGIN');try{const r=await Promise.all(list.map(q=>q.run()));sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
global.__testDb=database;global.__testFiles={async put(k,v){storage.set(k,v)},async delete(k){for(const key of Array.isArray(k)?k:[k])storage.delete(key)},async get(k){const b=storage.get(k);return b?{body:b,size:b.length}:null}};
fs.writeFileSync(out+'/lib/db.js',"exports.db=()=>global.__testDb;exports.files=()=>global.__testFiles;exports.settings=()=>({ADMIN_PIN:'test-pin-only',SESSION_SECRET:'a-very-long-random-test-only-session-secret'});");
const core=require(out+'/lib/communications.js'),route=require(out+'/app/api/community/route.js'),attachments=require(out+'/app/api/attachments/route.js'),auth=require(out+'/lib/admin-auth.js'),{prohibited}=require(out+'/lib/moderation.js');
const origin='https://school.test';let tests=0;async function req(body,cookie='',query=''){const r=new Request(origin+'/api/community'+query,{method:body?'POST':'GET',headers:{origin,cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const res=await route[body?'POST':'GET'](r);const data=await res.json();return {res,data}}
async function ok(body,cookie,query){const x=await req(body,cookie,query);assert.equal(x.res.status,200,JSON.stringify(x.data));tests++;return x}
async function denied(body,cookie,query){const x=await req(body,cookie,query);assert.ok(x.res.status>=400,'Expected access denial');tests++;return x}
(async()=>{
 for(const word of ['f*ck','sh!t','fuckyou','ياكسمك','fuck','f.u.c.k','FUUUCK','كـسـمك','كسمك','a7a','5awal','sharmouta'])assert.equal(prohibited(word),true,word);
 assert.equal(prohibited('a custom phrase',['custom phrase']),true);assert.equal(prohibited('stupid',[],['stupid']),false);
 for(const phrase of ['class assignment','Please add fruit to the canteen','ممكن اسال عن الواجب','شكرا لحضرتك'])assert.equal(prohibited(phrase),false,phrase);tests+=12;
 const first=await ok();const guest=first.res.headers.get('set-cookie').split(';')[0];const second=await ok();const other=second.res.headers.get('set-cookie').split(';')[0];
 const suggestion=(await ok({action:'suggest',anonymous:true,title:'More fruit',body:'Please add apples to the menu.'},guest)).data.id;
 assert.equal((await ok(null,other)).data.threads.length,0);await denied(null,other,'?thread='+suggestion);await denied({action:'send',thread:suggestion,body:'Intrusion'},other);
 await denied({action:'suggest',anonymous:false,name:'Name',title:'Bad word',body:'a7a'},guest);assert.equal(sql.prepare('SELECT COUNT(*) n FROM comm_threads').get().n,1);
 const until=String(Date.now()+3600000),admin='hb_admin='+until+'.'+await auth.signature(until);
 assert.equal((await ok(null,admin,'?staff=1')).data.threads.length,1);
 await ok({action:'status',thread:suggestion,status:'Not Possible',body:'The kitchen cannot store this safely.'},admin);
 const privateReply=(await ok(null,guest,'?thread='+suggestion)).data;assert.equal(privateReply.thread.status,'Not Possible');assert.match(privateReply.messages.at(-1).body,/cannot store/);assert.equal((await ok(null,other)).data.announcements.length,0);
 await denied({action:'announce',title:'Forged',body:'No school',effective:'2026-10-06'},guest);
 await ok({action:'announce',title:'Fresh fruit arrives',body:'Fruit cups are available next week.',effective:'2026-10-12'},admin);assert.equal((await ok(null,other)).data.announcements.length,1);
 for(const p of [{email:'student@els-egypt.info',name:'Student',role:'student',class_name:'8A'},{email:'other@els-egypt.info',name:'Other',role:'student',class_name:'8B'},{email:'teacher@els-egypt.info',name:'Teacher',role:'teacher',classes:'8A'},{email:'council@els-egypt.info',name:'Council',role:'council',class_name:'8A'}])await ok({action:'person',...p},admin);
 const cookieFor=async email=>'hb_identity='+await core.newSession(email,1);const student=await cookieFor('student@els-egypt.info'),teacher=await cookieFor('teacher@els-egypt.info'),outsider=await cookieFor('other@els-egypt.info'),council=await cookieFor('council@els-egypt.info');
 await denied({action:'person',email:'attacker@els-egypt.info',name:'Attacker',role:'staff'},student);
 assert.equal((await ok(null,student)).data.teachers.length,1);assert.equal((await ok(null,outsider)).data.teachers.length,0);
 await denied({action:'start',teacher:'teacher@els-egypt.info'},outsider);await denied({action:'start',teacher:'other@els-egypt.info'},student);
 const chat=(await ok({action:'start',teacher:'teacher@els-egypt.info'},student)).data.id;await ok({action:'send',thread:chat,body:'Could you explain the assignment?'},student);await ok({action:'send',thread:chat,body:'Of course. Which part?'},teacher);
 // Teachers receive only assigned students and can initiate conversations themselves.
 assert.equal((await ok(null,teacher)).data.contacts.some(p=>p.email==='other@els-egypt.info'),false);
 assert.ok((await ok(null,teacher)).data.contacts.some(p=>p.email==='student@els-egypt.info'));
 await denied({action:'start',student:'other@els-egypt.info'},teacher);
 assert.equal((await ok({action:'start',student:'student@els-egypt.info'},teacher)).data.id,chat);
 assert.equal((await ok(null,teacher,'?thread='+encodeURIComponent(chat))).data.thread.title,'Student');
 await ok({action:'person',email:'learner@els-egypt.info',name:'Learner',role:'student',class_name:'8A'},admin);
 const teacherStarted=(await ok({action:'start',student:'learner@els-egypt.info'},teacher)).data.id;
 assert.equal(sql.prepare('SELECT teacher FROM comm_threads WHERE id=?').get(teacherStarted).teacher,'teacher@els-egypt.info');
 tests+=3;
 await denied(null,outsider,'?thread='+encodeURIComponent(chat));await denied(null,council,'?thread='+encodeURIComponent(chat));await denied(null,admin,'?thread='+encodeURIComponent(chat));
 await denied({action:'send',thread:chat,body:'كسمك'},student);const messages=(await ok(null,teacher,'?thread='+encodeURIComponent(chat))).data.messages;assert.equal(messages.length,2);
 // Incremental delivery must preserve same-timestamp ordering and exclude private threads.
 await ok({action:'read',thread:chat},teacher);assert.ok((await ok(null,student,'?thread='+encodeURIComponent(chat))).data.recipientSeen>0);assert.equal((await ok(null,teacher,'?thread='+encodeURIComponent(chat))).data.recipientSeen,0);await ok({action:'read',thread:chat},student);assert.ok((await ok(null,teacher,'?thread='+encodeURIComponent(chat))).data.recipientSeen>0);
 const cursorMessage=messages.at(-1);const nextTime=cursorMessage.created+1;
 for(const id of ['cursor-a','cursor-b'])sql.prepare('INSERT INTO comm_messages(id,thread,sender,label,body,file,created) VALUES(?,?,?,?,?,?,?)').run(id,chat,'teacher@els-egypt.info','Teacher','Cursor '+id,'',nextTime);
 const deltaQuery='?thread='+encodeURIComponent(chat)+'&after='+nextTime+'&afterId=cursor-a';
 assert.deepEqual((await ok(null,student,deltaQuery)).data.messages.map(m=>m.id),['cursor-b']);
 assert.deepEqual((await ok(null,student,'?thread='+encodeURIComponent(chat)+'&after='+nextTime+'&afterId=cursor-b')).data.messages,[]);
 await denied(null,outsider,deltaQuery);await denied(null,student,'?thread='+encodeURIComponent(chat)+'&after=NaN');
 assert.equal((await ok(null,student)).data.threads.find(t=>t.id===chat).preview,'Cursor cursor-b');
 tests+=3;
 // Replies and history search remain scoped to a single authorized conversation.
 const replyId=messages[0].id;
 await ok({action:'send',thread:chat,body:'Thanks for explaining.',replyTo:replyId},student);
 const quoted=(await ok(null,teacher,'?thread='+encodeURIComponent(chat))).data.messages.at(-1);
 assert.equal(quoted.reply.id,replyId);assert.equal(quoted.reply.body,messages[0].body);
 await denied({action:'send',thread:chat,body:'Cross-thread quote',replyTo:privateReply.messages[0].id},student);
 const history=(await ok(null,teacher,'?thread='+encodeURIComponent(chat)+'&q='+encodeURIComponent('explaining'))).data.messages;
 assert.equal(history.length,1);assert.equal(history[0].id,quoted.id);
 await denied(null,outsider,'?thread='+encodeURIComponent(chat)+'&q=explaining');
 // Teachers can preview or download the exact bytes sent by the student.
 const pdfBytes=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF');
 const pdfForm=new FormData();pdfForm.append('thread',chat);pdfForm.append('file',new File([pdfBytes],'assignment.pdf',{type:'application/pdf'}));
 const pdfUpload=await attachments.POST(new Request(origin+'/api/attachments',{method:'POST',headers:{origin,cookie:student},body:pdfForm}));assert.equal(pdfUpload.status,200);const pdfFile=await pdfUpload.json();
 await ok({action:'send',thread:chat,body:'Please review this PDF.',file:pdfFile.id},student);
 const pdfRead=async (who,download=false)=>attachments.GET(new Request(origin+'/api/attachments?id='+pdfFile.id+(download?'&download=1':''),{headers:{cookie:who}}));
 const preview=await pdfRead(teacher);assert.equal(preview.status,200);assert.equal(preview.headers.get('content-type'),'application/pdf');assert.match(preview.headers.get('content-disposition'),/^inline/);assert.deepEqual(Buffer.from(await preview.arrayBuffer()),pdfBytes);
 const downloaded=await pdfRead(teacher,true);assert.equal(downloaded.status,200);assert.match(downloaded.headers.get('content-disposition'),/^attachment/);assert.match(downloaded.headers.get('content-disposition'),/assignment.pdf/);assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),pdfBytes);
 assert.equal((await pdfRead(outsider,true)).status,403);assert.equal((await pdfRead('',true)).status,403);tests+=10;
 const form=new FormData();form.append('thread',chat);form.append('file',new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5XcAAAAASUVORK5CYII=','base64')],'photo.png',{type:'image/png'}));const upload=await attachments.POST(new Request(origin+'/api/attachments',{method:'POST',headers:{origin,cookie:student},body:form}));assert.equal(upload.status,200);const file=await upload.json();
 const getFile=async cookie=>attachments.GET(new Request(origin+'/api/attachments?id='+file.id,{headers:{cookie}}));assert.equal((await getFile(outsider)).status,403);assert.equal((await getFile(teacher)).status,404);await ok({action:'send',thread:chat,body:'Here is the image.',file:file.id},student);assert.equal((await getFile(teacher)).status,200);
 await denied({action:'send',thread:suggestion,body:'File',file:file.id},guest);await denied({action:'send',thread:chat,body:'reuse',file:file.id},teacher);
 const fake=new FormData();fake.append('thread',chat);fake.append('file',new File(['<script>alert(1)</script>'],'bad.jpg',{type:'image/jpeg'}));assert.equal((await attachments.POST(new Request(origin+'/api/attachments',{method:'POST',headers:{origin,cookie:student},body:fake}))).status,400);
 await ok({action:'report',thread:chat,message:messages[0].id,reason:'Please review this message.'},teacher);assert.equal((await ok(null,council,'?staff=1')).data.reports,undefined);assert.equal((await ok(null,admin,'?staff=1')).data.reports.length,1);
 await ok({action:'person',email:'student@els-egypt.info',name:'Student',role:'student',class_name:'8B'},admin);await denied({action:'send',thread:chat,body:'Old access'},student);assert.equal((await ok(null,student)).data.threads.length,0);
 const jose=await import(root+'/node_modules/jose/dist/webapi/index.js');const keypair=await jose.generateKeyPair('RS256');const jwk=await jose.exportJWK(keypair.publicKey);jwk.kid='test-key';jwk.alg='RS256';global.fetch=async()=>Response.json({keys:[jwk]});const schoolAuth=require(out+'/app/api/school-auth/route.js');await ok({action:'configure',googleClientId:'test-client.apps.googleusercontent.com',blocked:'',allowed:''},admin);let nonce='';const token=async payload=>{sql.exec('DELETE FROM attempts');const begin=await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin},body:JSON.stringify({action:'begin'})}));assert.equal(begin.status,200);nonce=(await begin.json()).nonce;return new jose.SignJWT({email:'new@els-egypt.info',email_verified:true,hd:'els-egypt.info',nonce,...payload}).setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer('https://accounts.google.com').setAudience('test-client.apps.googleusercontent.com').setIssuedAt().setExpirationTime('5m').setSubject(payload.sub||'subject-'+(payload.email||'new@els-egypt.info')).sign(keypair.privateKey)};const login=async credential=>schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin,cookie:'hb_google_nonce='+nonce},body:JSON.stringify({credential,name:'New Student'})}));const firstCredential=await token({});const firstLogin=await login(firstCredential);assert.equal(firstLogin.status,200);const signedCookie=firstLogin.headers.getSetCookie().find(c=>c.startsWith('hb_identity=')).split(';')[0];assert.match(firstLogin.headers.getSetCookie().join(' '),/HttpOnly; Secure; SameSite=Lax/);assert.equal((await login(firstCredential)).status,403);tests+=2;
 const replaced=await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin,cookie:'hb_google_nonce='+nonce},body:JSON.stringify({action:'begin'})}));assert.equal(replaced.status,200);assert.equal(sql.prepare('SELECT nonce FROM auth_challenges WHERE nonce=?').get(await core.hash(nonce)),undefined);nonce=(await replaced.json()).nonce;sql.prepare('UPDATE auth_challenges SET expires=0 WHERE nonce=?').run(await core.hash(nonce));const expiredCredential=await new jose.SignJWT({email:'new@els-egypt.info',email_verified:true,hd:'els-egypt.info',nonce}).setSubject('subject-new@els-egypt.info').setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer('https://accounts.google.com').setAudience('test-client.apps.googleusercontent.com').setIssuedAt().setExpirationTime('5m').sign(keypair.privateKey);assert.equal((await login(expiredCredential)).status,403);tests+=3;
 const concurrentCredential=await token({});const concurrent=await Promise.all([login(concurrentCredential),login(concurrentCredential)]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,403]);tests++;
 const oldSession=await core.newSession('new@els-egypt.info',1);const rotationCredential=await token({});const rotated=await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin,cookie:'hb_google_nonce='+nonce+'; hb_identity='+oldSession},body:JSON.stringify({credential:rotationCredential,name:'New Student'})}));assert.equal(rotated.status,200);assert.equal(await core.session(new Request(origin,{headers:{cookie:'hb_identity='+oldSession}}),'hb_identity'),'');tests+=2;
 const crossOrigin=await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin:'https://other.test'},body:JSON.stringify({action:'begin'})}));assert.equal(crossOrigin.status,403);tests++;
 const recycled=await token({sub:'recycled-account'});assert.equal((await login(recycled)).status,403);tests++;
 const logout=await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin,cookie:signedCookie+'; hb_admin=old; hb_google_nonce='+nonce},body:JSON.stringify({action:'logout'})}));assert.equal(logout.status,200);assert.equal(await core.session(new Request(origin,{headers:{cookie:signedCookie}}),'hb_identity'),'');assert.ok(logout.headers.getSetCookie().some(c=>c.startsWith('hb_admin=;')));assert.ok(logout.headers.getSetCookie().some(c=>c.startsWith('hb_google_nonce=;')));tests+=4;
 sql.exec('DELETE FROM attempts');for(let i=0;i<20;i++)await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin},body:'invalid-json'}));const throttled=await schoolAuth.POST(new Request(origin+'/api/school-auth',{method:'POST',headers:{origin},body:JSON.stringify({action:'begin'})}));assert.equal(throttled.status,429);assert.equal(throttled.headers.get('retry-after'),'60');tests+=2;assert.equal((await login(await token({hd:'outside.info'}))).status,403);assert.equal((await login(await token({email_verified:false}))).status,403);assert.equal((await login(await token({nonce:'wrong'}))).status,403);const wrongAudience=await new jose.SignJWT({email:'new@els-egypt.info',email_verified:true,hd:'els-egypt.info',nonce}).setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer('https://accounts.google.com').setAudience('wrong').setIssuedAt().setExpirationTime('5m').sign(keypair.privateKey);assert.equal((await login(wrongAudience)).status,400);assert.equal(sql.prepare('SELECT role,class_name FROM comm_people WHERE email=?').get('new@els-egypt.info').role,'student');tests+=6;

 // Reliability: recovery, account-linked suggestions, permissions, idempotency, publishing and content edits.
 sql.exec('DELETE FROM attempts');
 const recovery=(await ok({action:'recovery'},guest)).data.code;
 await denied({action:'recover',code:'incorrect'},other);
 const recovered=(await ok({action:'recover',code:recovery},other)).res.headers.get('set-cookie').split(';')[0];
 assert.ok((await ok(null,recovered)).data.threads.some(t=>t.id===suggestion));
 const studentGuest=(await ok(null,student)).res.headers.get('set-cookie').split(';')[0];
 const named=(await ok({action:'suggest',anonymous:false,name:'Student',title:'Named suggestion',body:'Please improve the courtyard.',category:'Facilities'},student+'; '+studentGuest)).data.id;
 assert.ok((await ok(null,student)).data.threads.some(t=>t.id===named));await denied(null,outsider,'?thread='+named);
 const pending=(await ok({action:'announce',title:'Council proposal',body:'A proposed update.',effective:'2026-12-01',stage:'Published'},council)).data;assert.equal(pending.stage,'Pending approval');assert.equal((await ok(null,other)).data.announcements.length,1);
 const announcement=(await ok(null,admin,'?staff=1')).data.manageAnnouncements.find(a=>a.title==='Council proposal');await ok({action:'announce',id:announcement.id,title:announcement.title,body:announcement.description,effective:announcement.effective,stage:'Published'},admin);assert.equal((await ok(null,other)).data.announcements.length,2);
 await ok({action:'note',thread:suggestion,body:'Internal review note'},admin);assert.equal((await ok(null,guest,'?thread='+suggestion)).data.notes.length,0);assert.equal((await ok(null,admin,'?thread='+suggestion+'&staff=1')).data.notes.length,1);
 await ok({action:'assign',thread:suggestion,assignee:'council@els-egypt.info'},admin);
 await ok({action:'person',email:'student@els-egypt.info',name:'Student',role:'student',class_name:'8A'},admin);
 await ok({action:'send',thread:chat,body:'One message only',requestId:'retry-test-request-123'},student);await ok({action:'send',thread:chat,body:'One message only',requestId:'retry-test-request-123'},student);assert.equal(sql.prepare('SELECT COUNT(*) n FROM comm_messages WHERE body=?').get('One message only').n,1);
 const malformed=new FormData();malformed.append('thread',chat);malformed.append('file',new File([new Uint8Array([80,75,3,4])],'bad.docx'));assert.equal((await attachments.POST(new Request(origin+'/api/attachments',{method:'POST',headers:{origin,cookie:student},body:malformed}))).status,400);
 const validate=require(out+'/lib/file-validation.js').validateFile,fflate=require('fflate');assert.match(validate(fflate.zipSync({'[Content_Types].xml':fflate.strToU8('<Types/>'),'word/document.xml':fflate.strToU8('<document/>')}),'test.docx',''),/wordprocessingml/);assert.throws(()=>validate(fflate.zipSync({'[Content_Types].xml':fflate.strToU8('<Types/>'),'word/document.xml':fflate.strToU8('<document/>'),'word/vbaProject.bin':new Uint8Array([1])}),'macro.docx',''));
 const board=require(out+'/app/api/board/route.js');const bpost=async(body,cookie=admin)=>{const res=await board.POST(new Request(origin+'/api/board?grade=8&class=8A&student=anon_test',{method:'POST',headers:{origin,cookie},body:JSON.stringify({student:'anon_test',...body})}));return {res,data:await res.json()}};
 const scope={is_global:false,target_grades:[8],target_classes:[],excluded_classes:[]};const poll={kind:'poll',title:'Verified vote',audience:scope,options:['One','Two'],end:'2030-12-01T12:00:00Z',verified:true,stage:'Published'};assert.equal((await bpost({action:'create',item:poll})).res.status,200);const pollRow=sql.prepare("SELECT id FROM content WHERE kind='poll' AND json_extract(data,'$.title')='Verified vote'").get();assert.equal((await bpost({action:'vote',id:pollRow.id,value:[0]},other)).res.status,403);assert.equal((await bpost({action:'vote',id:pollRow.id,value:[0]},student)).res.status,200);assert.equal((await bpost({action:'vote',id:pollRow.id,value:[0]},student)).data.already,true);assert.equal((await bpost({action:'update',id:pollRow.id,item:{...poll,options:['Changed','Two']}})).res.status,400);
 const voted=()=>board.GET(new Request(origin+'/api/board?grade=8&class=8A&student=anon_test',{headers:{cookie:student}})).then(r=>r.json()).then(d=>d.items.find(i=>i.id===pollRow.id));
 assert.deepEqual((await voted()).counts,[1,0]);assert.equal((await bpost({action:'vote',id:pollRow.id,value:[]},other)).res.status,403);assert.equal((await voted()).total,1);
 assert.equal((await bpost({action:'vote',id:pollRow.id,value:[]},student)).data.withdrawn,true);assert.deepEqual((await voted()).counts,[0,0]);assert.equal((await voted()).total,0);
 assert.equal((await bpost({action:'vote',id:pollRow.id,value:[1]},student)).res.status,200);assert.deepEqual((await voted()).counts,[0,1]);assert.equal((await voted()).total,1);
 assert.equal((await bpost({action:'vote',id:pollRow.id,value:[0]},student)).res.status,200);assert.deepEqual((await voted()).counts,[1,0]);assert.equal((await voted()).total,1);
 const storedPoll=JSON.parse(sql.prepare('SELECT data FROM content WHERE id=?').get(pollRow.id).data);sql.prepare('UPDATE content SET data=? WHERE id=?').run(JSON.stringify({...storedPoll,end:'2020-01-01T00:00:00Z'}),pollRow.id);assert.equal((await bpost({action:'vote',id:pollRow.id,value:[]},student)).res.status,400);assert.equal((await bpost({action:'vote',id:pollRow.id,value:[1]},student)).res.status,400);assert.deepEqual((await voted()).counts,[1,0]);tests+=15;
 const event={kind:'event',title:'Editable event',category:'Class Event',audience:scope,start:'2030-01-01T09:00:00Z',end:'2030-01-01T10:00:00Z',stage:'Draft'};await bpost({action:'create',item:event});const eid=sql.prepare("SELECT id FROM content WHERE json_extract(data,'$.title')='Editable event'").get().id;const publicBoard=()=>board.GET(new Request(origin+'/api/board?grade=8&class=8A&student=anon_test')).then(r=>r.json());assert.equal((await publicBoard()).items.some(i=>i.id===eid),false);assert.equal((await bpost({action:'update',id:eid,item:{...event,stage:'Published'}})).res.status,200);assert.equal((await publicBoard()).items.some(i=>i.id===eid),true);await bpost({action:'archive',id:eid});assert.equal((await publicBoard()).items.some(i=>i.id===eid),false);
 await ok({action:'import',rows:[{name:'Import student',email:'import@els-egypt.info',role:'student',class_name:'9A'}]},admin);assert.equal(sql.prepare('SELECT class_name FROM comm_people WHERE email=?').get('import@els-egypt.info').class_name,'9A');
 await ok({action:'forget'},recovered);await denied(null,recovered,'?thread='+suggestion);
 assert.ok((await ok(null,admin)).data.audit.length>0);tests+=16;
 sql.exec('DELETE FROM attempts');await ok({action:'configure',googleClientId:'test-client.apps.googleusercontent.com',blocked:'',allowed:'',retentionDays:90},admin);sql.prepare('UPDATE comm_threads SET updated=? WHERE id=?').run(Date.now()-100*86400000,suggestion);const cleanup=(await ok({action:'maintenance'},admin)).data;assert.equal(cleanup.closedSuggestions,1);await ok({action:'maintenance',confirm:true},admin);assert.equal(sql.prepare('SELECT id FROM comm_threads WHERE id=?').get(suggestion),undefined);assert.ok(sql.prepare('SELECT id FROM comm_threads WHERE id=?').get(chat));assert.ok(sql.prepare('SELECT id FROM comm_threads WHERE id=?').get(named));tests+=3;
 sql.exec('DELETE FROM attempts');await ok({action:'person',email:'admin@els-egypt.info',name:'School administrator',role:'administrator'},admin);const administratorLogin=await login(await token({email:'admin@els-egypt.info'}));assert.equal(administratorLogin.status,200);const administratorCookie=administratorLogin.headers.getSetCookie().find(c=>c.startsWith('hb_identity=')).split(';')[0];assert.equal((await ok(null,administratorCookie)).data.admin,true);assert.equal((await ok(null,admin)).data.admin,false);await denied({action:'person',email:'admin@els-egypt.info',name:'School administrator',role:'student'},administratorCookie);tests+=4;
 const csrf=await route.POST(new Request(origin+'/api/community',{method:'POST',headers:{origin:'https://evil.test'},body:'{}'}));assert.equal(csrf.status,403);
 console.log(`PASS: ${tests}+ checks — anonymous privacy, private decisions, global announcements, role and class authorization, text filtering, attachment access, file signature checks, reporting, revoked assignments, CSRF.`);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{sql.close();fs.rmSync(out,{recursive:true,force:true})});
