import {db} from '@/lib/db';
import {identity,json,limit,clean} from '@/lib/communications';
import {visible,type Item} from '@/lib/board';
import {collectionAccess,collectorClasses,studentTripAccess} from '@/lib/trips';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{const c=await identity(r);if(!c.person&&!c.isAdmin)return json({mine:{},canCollect:false});const d=db();const trips=(await d.prepare("SELECT data FROM content WHERE kind='event'").all<{data:string}>()).results.map(x=>JSON.parse(x.data) as Item).filter(i=>i.category==='Trip');const own=c.person?(await d.prepare('SELECT trip,choice,updated FROM trip_interest WHERE actor=?').bind(c.person.email).all<{trip:string;choice:string;updated:number}>()).results:[];const mine=Object.fromEntries(own.filter(x=>trips.some(i=>i.id===x.trip&&studentTripAccess(i,c))).map(x=>[x.trip,{choice:x.choice,updated:x.updated}]));const canCollect=collectionAccess(c);if(new URL(r.url).searchParams.get('manage')!=='1')return json({mine,canCollect});if(!canCollect)return json({error:'Staff collection access required.'},403);
const classes=collectorClasses(c),eligible=trips.filter(i=>!i.sample&&['Published','Cancelled','Archived'].includes(i.stage||'Published')&&(classes===null||classes.some(cl=>visible(i.audience,Number(cl.slice(0,-1)),cl))));const interests=(await d.prepare("SELECT i.trip,i.choice,i.updated,p.name,p.class_name FROM trip_interest i JOIN comm_people p ON p.email=i.actor WHERE p.active=1 AND p.role IN ('student','council') ORDER BY p.class_name,p.name,i.actor").all<{trip:string;choice:string;updated:number;name:string;class_name:string}>()).results;
return json({mine,canCollect:true,trips:eligible.map(i=>{const students=interests.filter(x=>x.trip===i.id&&x.choice==='interested'&&!!x.class_name&&(classes===null||classes.includes(x.class_name))&&visible(i.audience,Number(x.class_name.slice(0,-1)),x.class_name)).map(({trip,choice,...s})=>s);return {id:i.id,title:i.title,start:i.start,end:i.end,stage:i.stage||'Published',cost:i.cost,deadline:i.deadline,students,total:students.length}})});
}catch{return json({error:'Unable to load trip responses.'},503)}}
export async function POST(r:Request){try{if(r.headers.get('origin')!==new URL(r.url).origin)return json({error:'Request not allowed.'},403);const c=await identity(r);if(!c.person)return json({error:'Sign in with your school account first.'},401);if(!['student','council'].includes(c.person.role)||!c.person.class_name)return json({error:'A verified student account with an assigned class is required.'},403);const raw=await r.text();if(raw.length>1000)return json({error:'Request too large.'},413);const b=JSON.parse(raw);if(!['interested','declined'].includes(b.choice))throw Error('Choose whether you want to participate.');await limit('trip-interest:'+c.person.email,30);const row=await db().prepare("SELECT data FROM content WHERE id=? AND kind='event'").bind(clean(b.trip,100)).first<{data:string}>();if(!row)return json({error:'Trip unavailable.'},404);const trip=JSON.parse(row.data) as Item;if(trip.category!=='Trip'||!studentTripAccess(trip,c))return json({error:'Trip unavailable for your assigned class.'},403);if(trip.sample)return json({error:'This is a sample trip. Staff must publish a real trip before collecting responses.'},400);if(trip.stage==='Cancelled')return json({error:'This trip is cancelled.'},409);if(!trip.start||!(Date.parse(trip.start)>Date.now()))return json({error:'Responses close when the trip starts.'},409);const now=Date.now();await db().prepare('INSERT INTO trip_interest(trip,actor,choice,created,updated) VALUES(?,?,?,?,?) ON CONFLICT(trip,actor) DO UPDATE SET choice=excluded.choice,updated=excluded.updated').bind(trip.id,c.person.email,b.choice,now,now).run();return json({ok:true,trip:trip.id,choice:b.choice,updated:now});
}catch(e){return json({error:e instanceof Error?e.message:'Unable to save your trip response.'},400)}}
