import {db,files} from '@/lib/db';
import {DOMAIN,states,json,clean,identity,threadAccess,config,moderate,limit,random,newSession,setCookie,addMessage,hash,cookie,recordAudit} from '@/lib/communications';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{const c=await identity(r),u=new URL(r.url),d=db(),cfg=await config();let guestCookie='';if(!c.guest&&!u.searchParams.has('thread')){c.guest='guest:'+random();guestCookie=setCookie('hb_guest',await newSession(c.guest,365),31536000);if(!c.actor)c.actor=c.guest}
 const email=c.person?.email||'__no_account__';
 if(u.searchParams.has('thread')){const t=await threadAccess(clean(u.searchParams.get('thread')),c);const before=Number(u.searchParams.get('before')||Number.MAX_SAFE_INTEGER),beforeId=u.searchParams.get('beforeId')||'\uffff';if(!Number.isFinite(before))throw Error('Invalid message cursor.');const afterRaw=u.searchParams.get('after'),after=Number(afterRaw),afterId=u.searchParams.get('afterId')||'';if(afterRaw!==null&&(!Number.isFinite(after)||after<0))throw Error('Invalid message cursor.');const incremental=afterRaw!==null&&!u.searchParams.has('before');const rows=incremental?await d.prepare('SELECT m.*,f.name filename,f.mime,f.size FROM comm_messages m LEFT JOIN comm_files f ON f.id=m.file WHERE m.thread=? AND (m.created>? OR (m.created=? AND m.id>?)) ORDER BY m.created ASC,m.id ASC LIMIT 101').bind(t.id,after,after,afterId).all<any>():await d.prepare('SELECT m.*,f.name filename,f.mime,f.size FROM comm_messages m LEFT JOIN comm_files f ON f.id=m.file WHERE m.thread=? AND (m.created<? OR (m.created=? AND m.id<?)) ORDER BY m.created DESC,m.id DESC LIMIT 101').bind(t.id,before,before,beforeId).all<any>();const notes=c.moderator&&u.searchParams.get('staff')==='1'?(await d.prepare('SELECT * FROM comm_notes WHERE thread=? ORDER BY created DESC LIMIT 100').bind(t.id).all()).results:[];const recipient=t.kind==='chat'?(email===t.owner?t.teacher:t.owner):'';const receipt=recipient?await d.prepare('SELECT seen FROM comm_reads WHERE thread=? AND actor=?').bind(t.id,recipient).first<{seen:number}>():null;return json({recipientSeen:receipt?.seen||0,thread:{id:t.id,title:t.title,status:t.status,kind:t.kind,name:t.name,category:t.category,assignee:t.assignee},notes,hasOlder:!incremental&&rows.results.length>100,hasNewer:incremental&&rows.results.length>100,messages:(incremental?rows.results.slice(0,100):rows.results.slice(0,100).reverse()).map(m=>({id:m.id,body:m.body,label:m.label,created:m.created,mine:m.sender===email||m.sender===c.guest||m.sender===c.actor||m.sender===t.owner&&t.account===email,file:m.file?{id:m.file,name:m.filename,mime:m.mime,size:m.size}:null}))})}
 const scope=u.searchParams.get('staff')==='1'&&c.moderator;
 const people=(await d.prepare('SELECT * FROM comm_people WHERE active=1').all<any>()).results;const teachers=c.person?.class_name?people.filter(t=>['teacher','staff'].includes(t.role)&&JSON.parse(t.classes).includes(c.person!.class_name)).map(t=>({email:t.email,name:t.name})):[];
 const page=Math.max(0,Math.min(10000,Number(u.searchParams.get('page'))||0));const search=(u.searchParams.get('q')||'').slice(0,100);
 const eligibility="((t.kind='suggestion' AND (t.owner=? OR t.account=? OR ?=1)) OR (t.kind='chat' AND (t.owner=? OR t.teacher=?) AND EXISTS (SELECT 1 FROM comm_people s JOIN comm_people p ON p.email=t.teacher JOIN json_each(p.classes) cls ON cls.value=s.class_name WHERE s.email=t.owner AND s.active=1 AND p.active=1 AND p.role IN ('teacher','staff'))))";
 const args=[c.guest,email,scope?1:0,email,email];
 const rows=(await d.prepare("SELECT t.*, (SELECT CASE WHEN m.body<>'' THEN substr(m.body,1,140) WHEN m.file<>'' THEN 'Attachment' ELSE '' END FROM comm_messages m WHERE m.thread=t.id ORDER BY m.created DESC,m.id DESC LIMIT 1) preview, (SELECT COUNT(*) FROM comm_messages m WHERE m.thread=t.id AND m.created>COALESCE((SELECT seen FROM comm_reads WHERE thread=t.id AND actor=?),0) AND m.sender<>? AND m.sender<>? AND NOT(m.sender=t.owner AND t.account=?)) unread FROM comm_threads t WHERE "+eligibility+" AND (t.title LIKE ? OR t.name LIKE ?) ORDER BY t.updated DESC,t.id DESC LIMIT 51 OFFSET ?").bind(c.actor||c.guest,c.actor||c.guest,c.guest,email,...args,'%'+search+'%','%'+search+'%',page*50).all<any>()).results;
 const counts=(await d.prepare("SELECT t.kind,COUNT(*) total FROM comm_messages m JOIN comm_threads t ON t.id=m.thread WHERE "+eligibility+" AND m.created>COALESCE((SELECT seen FROM comm_reads WHERE thread=t.id AND actor=?),0) AND m.sender<>? AND m.sender<>? AND NOT(m.sender=t.owner AND t.account=?) GROUP BY t.kind").bind(...args,c.actor||c.guest,c.actor||c.guest,c.guest,email).all<any>()).results;
 const unread={chat:counts.find(x=>x.kind==='chat')?.total||0,suggestion:counts.find(x=>x.kind==='suggestion')?.total||0};
 if(u.searchParams.get('summary')==='1')return json({unread},200,guestCookie?{'Set-Cookie':guestCookie}:{});
 const allAnnouncements=(await d.prepare("SELECT data FROM content WHERE kind='announcement'").all<{data:string}>()).results.map(x=>JSON.parse(x.data)).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||b.created-a.created);
 const announcements=allAnnouncements.filter(a=>(!a.stage||a.stage==='Published')&&(!a.expiry||Date.parse(a.expiry+'T23:59:59+02:00')>Date.now()));
 const response:any={person:c.person?{...c.person,classes:JSON.parse(c.person.classes)}:null,moderator:c.moderator,staff:c.staff,admin:c.isAdmin,teachers,threads:rows.slice(0,50).map(t=>({id:t.id,kind:t.kind,title:t.kind==='chat'&&email===t.teacher?t.name:t.title,name:t.name,status:t.status,category:t.category,assignee:t.assignee,updated:t.updated,unread:t.unread,preview:t.preview||''})),hasMore:rows.length>50,page,unread,announcements,googleClientId:cfg.googleClientId||'',domain:DOMAIN};
 if(c.moderator){response.manageAnnouncements=allAnnouncements;response.team=people.filter(p=>['staff','council','administrator'].includes(p.role)).map(p=>({name:p.name,email:p.email}));}
 if(c.isAdmin){response.roster=(await d.prepare('SELECT * FROM comm_people ORDER BY role,name').all()).results;response.blocked=JSON.parse(cfg.blocked||'[]');response.allowed=JSON.parse(cfg.allowed||'[]');response.audit=(await d.prepare('SELECT * FROM comm_audit ORDER BY created DESC LIMIT 100').all()).results;response.retentionDays=Number(cfg.retentionDays||0)}
 if(c.staff&&scope)response.reports=(await d.prepare('SELECT r.id,r.reason,r.created,r.resolved,m.body,m.label,m.file,f.name filename,f.mime,f.size FROM comm_reports r JOIN comm_messages m ON m.id=r.message LEFT JOIN comm_files f ON f.id=m.file ORDER BY r.created DESC LIMIT 100').all()).results;
 return json(response,200,guestCookie?{'Set-Cookie':guestCookie}:{});
 }catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Unable to load messages.'},e instanceof Error&&/Conversation unavailable|class assignment has changed|School sign-in required/.test(e.message)?403:400)}}
export async function POST(r:Request){try{if(r.headers.get('origin')!==new URL(r.url).origin)return json({error:'Request not allowed'},403);const raw=await r.text();if(raw.length>20000)return json({error:'Request too large'},413);const b=JSON.parse(raw),c=await identity(r),d=db();await limit(c.actor||r.headers.get('cf-connecting-ip')||'guest');if(!c.person&&!c.isAdmin)await limit('ip:'+(r.headers.get('cf-connecting-ip')||'local'),100);
 if(b.action==='recovery'){if(!c.guest)throw Error('Open your inbox first.');const token=random();await d.prepare('INSERT INTO comm_recovery(token,owner,created) VALUES(?,?,?)').bind(await hash(token),c.guest,Date.now()).run();return json({code:token})}
 if(b.action==='recover'){await limit('recover:'+(r.headers.get('cf-connecting-ip')||'local'),5);const code=clean(b.code,100).replace(/\s/g,'');const row=await d.prepare('SELECT owner FROM comm_recovery WHERE token=?').bind(await hash(code)).first<{owner:string}>();if(!row)throw Error('Recovery code not recognized.');return json({ok:true},200,{'Set-Cookie':setCookie('hb_guest',await newSession(row.owner,365),31536000)})}
 if(b.action==='forget'){const token=cookie(r,'hb_guest');if(token)await d.prepare('DELETE FROM comm_sessions WHERE token=?').bind(await hash(token)).run();return json({ok:true},200,{'Set-Cookie':setCookie('hb_guest','',0)})}
 if(b.action==='maintenance'){if(!c.isAdmin)throw Error('Administrator access required.');const cfg=await config(),days=Number(cfg.retentionDays||0);const cutoff=days>0?Date.now()-days*86400000:0;const old=(await d.prepare("SELECT id FROM comm_threads WHERE kind='suggestion' AND status IN ('Not Possible','Implemented') AND updated<? LIMIT 100").bind(cutoff).all<{id:string}>()).results;const orphan=(await d.prepare('SELECT id,object_key FROM comm_files WHERE created<? AND NOT EXISTS(SELECT 1 FROM comm_messages WHERE file=comm_files.id) LIMIT 100').bind(Date.now()-86400000).all<any>()).results;if(!b.confirm)return json({closedSuggestions:old.length,abandonedFiles:orphan.length,retentionDays:days});if(orphan.length){await files().delete(orphan.map(f=>f.object_key));await d.prepare('DELETE FROM comm_files WHERE id IN ('+orphan.map(()=>'?').join(',')+')').bind(...orphan.map(f=>f.id)).run()}if(old.length){const ids=old.map(t=>t.id),marks=ids.map(()=>'?').join(',');await d.batch([d.prepare('DELETE FROM comm_notes WHERE thread IN ('+marks+')').bind(...ids),d.prepare('DELETE FROM comm_reads WHERE thread IN ('+marks+')').bind(...ids),d.prepare('DELETE FROM comm_reports WHERE message IN (SELECT id FROM comm_messages WHERE thread IN ('+marks+'))').bind(...ids),d.prepare('DELETE FROM comm_messages WHERE thread IN ('+marks+')').bind(...ids),d.prepare('DELETE FROM comm_threads WHERE id IN ('+marks+')').bind(...ids)])}await d.prepare('DELETE FROM comm_sessions WHERE expires<?').bind(Date.now()).run();await recordAudit(c,'Maintenance cleanup',old.length+' suggestions; '+orphan.length+' files');return json({ok:true})}
 if(b.action==='import'){if(!c.isAdmin)throw Error('Administrator access required.');if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>100)throw Error('Use 1–100 roster rows.');const adminEmails=new Set((await d.prepare("SELECT email FROM comm_people WHERE role='administrator'").all<{email:string}>()).results.map(p=>p.email));const seen=new Set<string>();const statements=b.rows.map((p:any)=>{const email=clean(p.email,150).toLowerCase(),name=clean(p.name,80),role=p.role,cls=String(p.class_name||'').toUpperCase().trim(),classes=String(p.classes||'').split(',').map((v:string)=>v.toUpperCase().trim()).filter(Boolean);if(!/^[a-z0-9._%+-]+@els-egypt\.info$/.test(email)||seen.has(email)||!['student','teacher','council','staff'].includes(role))throw Error('Check duplicate emails, school domains and roles.');if(adminEmails.has(email))throw Error('Administrator accounts must be edited individually.');seen.add(email);if(role==='administrator')throw Error('Add administrator accounts individually.');if([cls,...classes].filter(Boolean).some(v=>!/^([1-9]|1[0-2])[A-Z]$/.test(v)))throw Error('Check the class codes.');return d.prepare('INSERT INTO comm_people(email,name,role,class_name,classes,active) VALUES(?,?,?,?,?,1) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,class_name=excluded.class_name,classes=excluded.classes,active=1').bind(email,name,role,cls,JSON.stringify(classes))});await d.batch(statements);await recordAudit(c,'Roster imported',b.rows.length+' accounts');return json({ok:true})}
 if(b.action==='configure'||b.action==='person'){if(!c.isAdmin)return json({error:'Administrator access required.'},403);if(b.action==='configure'){const id=String(b.googleClientId||'').trim();if(id&&!/^[\w-]+\.apps\.googleusercontent\.com$/.test(id))throw Error('Enter a Google web client ID.');const blocked=String(b.blocked||'').split('\n').map(s=>s.trim()).filter(Boolean).slice(0,200),allowed=String(b.allowed||'').split('\n').map(s=>s.trim()).filter(Boolean).slice(0,200);await d.batch(Object.entries({googleClientId:id,blocked:JSON.stringify(blocked),allowed:JSON.stringify(allowed),retentionDays:String([0,90,180,365].includes(Number(b.retentionDays))?Number(b.retentionDays):0)}).map(([key,value])=>d.prepare('INSERT INTO comm_config(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,value)));}else{const email=clean(b.email,150).toLowerCase();if(!/^[a-z0-9._%+-]+@els-egypt\.info$/.test(email))throw Error('Use an els-egypt.info email.');if(!['student','teacher','staff','council','administrator'].includes(b.role))throw Error('Choose a valid role.');const current=await d.prepare('SELECT role FROM comm_people WHERE email=?').bind(email).first<{role:string}>();if(current?.role==='administrator'&&(b.role!=='administrator'||b.active===false)){const count=await d.prepare("SELECT COUNT(*) n FROM comm_people WHERE role='administrator' AND active=1").first<{n:number}>();if((count?.n||0)<=1)throw Error('Keep at least one enabled administrator. Add another administrator first.');}const classes=String(b.classes||'').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);const cls=String(b.class_name||'').trim().toUpperCase();if([...classes,...(cls?[cls]:[])].some(s=>!/^([1-9]|1[0-2])[A-Z]$/.test(s)))throw Error('Use class codes such as 8A, 8B.');await d.prepare('INSERT INTO comm_people(email,name,role,class_name,classes,active) VALUES(?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role,class_name=excluded.class_name,classes=excluded.classes,active=excluded.active').bind(email,clean(b.name,80),b.role,cls,JSON.stringify(classes),b.active===false?0:1).run()}await recordAudit(c,b.action==='person'?'Roster updated':'Settings updated',String(b.email||'configuration'));return json({ok:true})}
 if(b.action==='suggest'){if(!c.guest)throw Error('Refresh this page before submitting.');const body=clean(b.body);const name=b.anonymous?'Anonymous student':clean(b.name,80);const title=clean(b.title,120);await moderate(body+' '+name+' '+title);const id=crypto.randomUUID(),now=Date.now();const category=['General','Canteen','Events','Facilities','School rules'].includes(b.category)?b.category:'General';await d.batch([d.prepare("INSERT INTO comm_threads(id,kind,owner,name,teacher,title,status,updated,account,category) VALUES(?,'suggestion',?,?,'',?,'Received',?,?,?)").bind(id,c.guest,name,title,now,!b.anonymous?c.person?.email||'':'',category),d.prepare('INSERT INTO comm_messages(id,thread,sender,label,body,file,created) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,c.guest,name,body,'',now)]);return json({ok:true,id})}
 if(b.action==='start'){if(!c.person||!['student','council'].includes(c.person.role))throw Error('Sign in with your school student account.');const teacher=await d.prepare("SELECT * FROM comm_people WHERE email=? AND active=1 AND role IN ('teacher','staff')").bind(clean(b.teacher,150)).first<any>();if(!teacher||!c.person.class_name||!JSON.parse(teacher.classes).includes(c.person.class_name))throw Error('This teacher is not assigned to your class.');const id=c.person.email+':'+teacher.email;await d.prepare("INSERT OR IGNORE INTO comm_threads(id,kind,owner,name,teacher,title,status,updated) VALUES(?,'chat',?,?,?,?,'Open',?)").bind(id,c.person.email,c.person.name,teacher.email,teacher.name,Date.now()).run();return json({ok:true,id})}
 if(b.action==='announce'){if(!c.moderator)throw Error('Council or staff access required.');const title=clean(b.title,160),body=clean(b.body),effective=clean(b.effective,30);if(!/^\d{4}-\d{2}-\d{2}$/.test(effective)||!Number.isFinite(Date.parse(effective)))throw Error('Choose an effective date.');await moderate(title+' '+body);let stage=['Draft','Pending approval','Published','Archived'].includes(b.stage)?b.stage:'Published';if(stage==='Published'&&!c.staff)stage='Pending approval';const id=b.id?clean(b.id):crypto.randomUUID();const existing=await d.prepare("SELECT data FROM content WHERE id=? AND kind='announcement'").bind(id).first<{data:string}>();if(b.id&&!existing)throw Error('Announcement unavailable.');if(existing&&!c.staff&&JSON.parse(existing.data).stage!=='Draft'&&JSON.parse(existing.data).stage!=='Pending approval')throw Error('Staff approval is required to change published announcements.');const item={id,kind:'announcement',title,description:body,effective,stage,pinned:!!b.pinned,expiry:b.expiry?clean(b.expiry,30):'',created:existing?JSON.parse(existing.data).created:Date.now(),updated:Date.now(),author:'High Board',audience:{is_global:true,target_grades:[],target_classes:[],excluded_classes:[]}};if(item.expiry&&(!/^\d{4}-\d{2}-\d{2}$/.test(item.expiry)||!Number.isFinite(Date.parse(item.expiry))))throw Error('Invalid expiry date.');await d.prepare('INSERT INTO content(id,kind,data) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,'announcement',JSON.stringify(item)).run();await recordAudit(c,'Announcement '+stage,id);return json({ok:true,stage})}
 if(b.action==='resolve'){if(!c.staff)throw Error('Council or staff access required.');await d.prepare('UPDATE comm_reports SET resolved=1 WHERE id=?').bind(clean(b.id)).run();return json({ok:true})}
 const t=await threadAccess(clean(b.thread),c);
 if(b.action==='read'){await d.prepare('INSERT INTO comm_reads(thread,actor,seen) VALUES(?,?,?) ON CONFLICT(thread,actor) DO UPDATE SET seen=excluded.seen').bind(t.id,c.actor||c.guest,Date.now()).run();return json({ok:true})}
 if(b.action==='report'){const message=await d.prepare('SELECT id FROM comm_messages WHERE id=? AND thread=?').bind(clean(b.message),t.id).first();if(!message)throw Error('Message unavailable.');await d.prepare('INSERT INTO comm_reports(id,message,actor,reason,created,resolved) VALUES(?,?,?,?,?,0)').bind(crypto.randomUUID(),b.message,c.actor||c.guest,clean(b.reason,500),Date.now()).run();return json({ok:true})}
 if(b.action==='note'){if(!c.moderator||t.kind!=='suggestion')throw Error('Council access required.');await d.prepare('INSERT INTO comm_notes(id,thread,author,body,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),t.id,c.person?.name||'Administration',clean(b.body),Date.now()).run();return json({ok:true})}
 if(b.action==='assign'){if(!c.moderator||t.kind!=='suggestion')throw Error('Council access required.');const who=String(b.assignee||'');if(who&&!await d.prepare("SELECT email FROM comm_people WHERE email=? AND active=1 AND role IN ('staff','council','administrator')").bind(who).first())throw Error('Choose a council or staff member.');await d.prepare('UPDATE comm_threads SET assignee=? WHERE id=?').bind(who,t.id).run();await recordAudit(c,'Assigned suggestion',t.id);return json({ok:true})}
 if(b.action==='status'){if(!c.moderator||t.kind!=='suggestion'||!states.includes(b.status))throw Error('Status update not allowed.');const explanation=clean(b.body);await moderate(explanation);await addMessage(t,c,`${b.status}: ${explanation}`,'',true,'',b.status);await recordAudit(c,'Decision: '+b.status,t.id);return json({ok:true})}
 if(b.action==='send'){const requestId=typeof b.requestId==='string'&&/^[a-zA-Z0-9-]{16,80}$/.test(b.requestId)?b.requestId:'';const sender=t.kind==='suggestion'&&(t.owner===c.guest||t.account===c.person?.email)&&!(b.asStaff&&c.moderator)?t.owner:t.kind==='chat'?c.person?.email:c.actor;if(requestId&&await d.prepare('SELECT id FROM comm_messages WHERE id=?').bind(await hash(t.id+'|'+sender+'|'+requestId)).first())return json({ok:true,already:true});const body=String(b.body||'').trim(),file=String(b.file||'');if(!body&&!file)throw Error('Write a message or attach a file.');if(body.length>4000)throw Error('Use 4,000 characters or fewer.');await moderate(body);if(file){if(t.kind!=='chat')throw Error('Suggestions accept text only.');const f=await d.prepare('SELECT id FROM comm_files WHERE id=? AND thread=? AND actor=?').bind(file,t.id,c.person?.email||'').first();if(!f)throw Error('Attachment unavailable.');const used=await d.prepare('SELECT id FROM comm_messages WHERE file=?').bind(file).first();if(used)throw Error('This attachment has already been sent.');}await addMessage(t,c,body,file,!!b.asStaff&&c.moderator,requestId);return json({ok:true})}
 throw Error('Unknown action.');
 }catch(e){console.error(e instanceof Error?e.message:e);return json({error:e instanceof Error?e.message:'Unable to save.'},400)}}
