'use client';
import {useEffect,useRef,type ReactNode} from 'react';
import {CalendarDays,GraduationCap,Home,MessageSquare,Shield,Utensils,Users,X} from 'lucide-react';
const routes=[{name:'Overview',label:'Home',icon:Home,group:'School'},{name:'Calendar',label:'Calendar',icon:CalendarDays,group:'School'},{name:'Schedules',label:'Assessments',icon:GraduationCap,group:'School'},{name:'Workspace',label:'My workspace',icon:Shield,group:'My account'},{name:'Messages',label:'Messages',icon:MessageSquare,group:'My account'},{name:'Student voice',label:'Student voice',icon:Users,group:'Student life'},{name:'Canteen',label:'Canteen',icon:Utensils,group:'Student life'},{name:'Admin',label:'Administration',icon:Shield,group:'Manage'}];
export function AppNavigation({brand,tab,onNavigate,open,onClose,teacher,admin,polls,role}:{brand:ReactNode;tab:string;onNavigate:(tab:string)=>void;open:boolean;onClose:()=>void;teacher:boolean;admin:boolean;polls:number;role:string}){
 const ref=useRef<HTMLElement>(null),close=useRef(onClose);close.current=onClose;
 useEffect(()=>{if(!open)return;const prior=document.activeElement as HTMLElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('.navigation [aria-current="page"]')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close.current();if(e.key==='Tab'){const controls=Array.from(ref.current?.querySelectorAll<HTMLElement>('a[href],button')||[]).filter(e=>!e.classList.contains('desktop-only'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);prior?.focus()}},[open]);
 const visible=routes.filter(r=>(r.name!=='Admin'||admin)&&(!teacher||!['Student voice','Canteen'].includes(r.name)));
 return <>{open&&<button className="navigation-backdrop" onClick={onClose} aria-label="Close navigation" tabIndex={-1}/>}<aside id="app-navigation" className={'desktop-rail app-sidebar'+(open?' menu-open':'')} ref={ref} role={open?'dialog':undefined} aria-modal={open?true:undefined} aria-label="School navigation"><div className="sidebar-brand">{brand}<button className="icon-button sidebar-close" onClick={onClose} aria-label="Close menu"><X size={22}/></button></div><div className="sidebar-school"><span>EAIS · New Cairo</span><small>2026–2027</small></div><nav className="navigation" aria-label="Main navigation">{['School','My account','Student life','Manage'].map(group=>{const items=visible.filter(r=>r.group===group);return items.length?<div className="navigation-group" key={group}><p>{group}</p>{items.map(({name,label,icon:Icon})=><button key={name} data-page={name} aria-current={tab===name?'page':undefined} className={tab===name?'active':''} onClick={()=>{onNavigate(name);onClose()}}><Icon size={20}/><span className="nav-long">{label}</span>{name==='Student voice'&&polls>0&&<span className="nav-count" aria-label={polls+' open polls'}>{polls}</span>}</button>)}</div>:null})}</nav><div className="sidebar-footer"><span className="account-role">{role}</span><p>School updates and student life</p><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/cookies">Cookies</a></div></div></aside></>
}
