'use client';
import {useEffect,useRef,useState} from 'react';
import {CalendarDays,CheckCircle2,MessageSquare,School,Utensils,X} from 'lucide-react';
const steps=[
 {page:'Overview',target:'.daily-today',icon:School,title:'Start with your school day',text:'Your home page brings together upcoming events, assessments, announcements and quick shortcuts.',tip:'Use the class button at the top to change your viewing profile. Teacher access comes from the school roster.'},
 {page:'Calendar',target:'.calendar',icon:CalendarDays,title:'Find dates without searching',text:'Choose a day to see its events. Switch between monthly, weekly and daily views.',tip:'Open an event for its details, then export it to your calendar.'},
 {page:'Schedules',target:'.assessment-filters',icon:School,title:'Keep your timetable close',text:'Schedules shows assessments and published school events for your class, with times and rooms.',tip:'Times are shown in Cairo time. A blank timetable means the school has not published it yet.'},
 {page:'Messages',target:'.comm-inbox,.demo-main',icon:MessageSquare,title:'Message a teacher',text:'Search your chats or choose an assigned teacher. Type a message, attach a file, or record a voice note.',tip:'School sign-in is required for real messages. The labelled demo stays on your device. Enter sends on desktop; Shift + Enter adds a line.'},
 {page:'Student voice',target:'.voice-tabs',icon:MessageSquare,title:'Have your say',text:'Use Private suggestions to send an idea to the council, or Council polls to vote on decisions.',tip:'Anonymous suggestions need a recovery code if you want to reopen them on another browser.'},
 {page:'Canteen',target:'.meal-grid',icon:Utensils,title:'Know what is available',text:'Check the menu, prices and availability. You can request a snack or leave feedback.',tip:'You are ready. You can reopen this guide from How to use at any time.'}
];
export function AppTutorial({onNavigate}:{onNavigate:(page:string)=>void}){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0);const box=useRef<HTMLDivElement>(null),prior=useRef<HTMLElement|null>(null);const current=steps[step];const Icon=current.icon;
 useEffect(()=>{const start=()=>{prior.current=document.activeElement as HTMLElement;setStep(0);setOpen(true)};window.addEventListener('hb-tutorial',start);return()=>window.removeEventListener('hb-tutorial',start)},[]);
 function close(){setOpen(false);requestAnimationFrame(()=>prior.current?.focus())}
 useEffect(()=>{if(!open)return;onNavigate(steps[step].page);box.current?.focus()},[open,step,onNavigate]);
 useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);prior.current?.focus()}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[open]);
 useEffect(()=>{if(!open)return;let target:Element|null=null;const timer=setTimeout(()=>{target=document.querySelector(steps[step].target);target?.classList.add('tour-highlight')},150);return()=>{clearTimeout(timer);target?.classList.remove('tour-highlight')}},[open,step]);
 if(!open)return null;
 return <div className="tutorial-overlay"><section className="tutorial-card" role="dialog" aria-modal="false" aria-labelledby="tutorial-title" aria-describedby="tutorial-description" tabIndex={-1} ref={box}><header><span>QUICK GUIDE</span><button className="icon-button" aria-label="Close tutorial" onClick={close}><X size={20}/></button></header><div className="tutorial-progress" aria-label={`Step ${step+1} of ${steps.length}`}>{steps.map((s,i)=><button key={s.title} aria-label={`Step ${i+1}: ${s.title}`} aria-current={i===step?'step':undefined} className={i<=step?'done':''} onClick={()=>setStep(i)}/>)}</div><div className="tutorial-content" key={step}><span className="tutorial-icon"><Icon size={30}/></span><small>{step+1} / {steps.length} · {current.page==='Messages'?'Teacher chat':current.page}</small><h2 id="tutorial-title">{current.title}</h2><p id="tutorial-description">{current.text}</p><div className="tutorial-tip"><CheckCircle2 size={19}/><p>{current.tip}</p></div></div><footer><button className="secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)}>Back</button><button className="primary" onClick={()=>step===steps.length-1?close():setStep(s=>s+1)}>{step===steps.length-1?'Finish guide':'Next'}</button></footer></section></div>
}
