'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Users,Smile,MessageSquare,Search,Lock,Check,CheckCheck,CheckCircle2,FileText,Mic,Paperclip,Send,Square,Trash2,X} from 'lucide-react';
import {FileAttachment} from '@/components/FileAttachment';
import {prohibited} from '@/lib/moderation';

type Role='student'|'teacher';
type Attachment={url:string;name:string;type:string;size:number};
type Message={id:number;role:Role;body:string;created:number;read:boolean;attachment?:Attachment};
const sampleChats=[{id:'math',student:'Ahmed',teacher:'Mr. Karim',subject:'Mathematics',className:'9E'},{id:'english',student:'Ahmed',teacher:'Ms. Salma',subject:'English',className:'9E'},{id:'omar',student:'Omar',teacher:'Mr. Karim',subject:'Mathematics',className:'9E'}];
const initial=():Message[]=>[{id:0,role:'teacher',body:'Hello Ahmed! You can send your question or share your proposal here. How can I help?',created:Date.now(),read:true}];
const size=(n:number)=>n>1024*1024?(n/1024/1024).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB';

export function TeacherChatDemo({onClose}:{onClose?:()=>void}={}){
 const [role,setRole]=useState<Role>('student'),[messages,setMessages]=useState<Message[]>(initial),[drafts,setDrafts]=useState({student:'',teacher:''}),[pending,setPending]=useState<Partial<Record<Role,Attachment>>>({}),[error,setError]=useState(''),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[starting,setStarting]=useState(false),[emojiOpen,setEmojiOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState('math'),[mobileList,setMobileList]=useState(false),[otherChats,setOtherChats]=useState<Record<string,Message[]>>({}),[otherDrafts,setOtherDrafts]=useState<Record<string,{student:string;teacher:string}>>({}),[otherFiles,setOtherFiles]=useState<Record<string,Partial<Record<Role,Attachment>>>>({});
 const history=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null),urls=useRef(new Set<string>()),nextId=useRef(1),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),alive=useRef(true),timer=useRef<ReturnType<typeof setInterval>|null>(null),totalBytes=useRef(0),recordBytes=useRef(0);
 const chat=sampleChats.find(c=>c.id===active)!;const names:Record<Role,string>={student:chat.student+' · Student',teacher:chat.teacher+' · Teacher'};const chats=sampleChats.filter(c=>role==='student'?c.student==='Ahmed':c.teacher==='Mr. Karim');
 function selectChat(id:string){if(recording||starting)return;if(id===active){setMobileList(false);return;}setOtherChats(p=>({...p,[active]:messages}));setOtherDrafts(p=>({...p,[active]:drafts}));setOtherFiles(p=>({...p,[active]:pending}));const target=sampleChats.find(c=>c.id===id)!;setActive(id);setMessages((otherChats[id]||[{id:0,role:'teacher',body:'Hello '+target.student+'! How can I help?',created:Date.now(),read:true}]).map(m=>m.role!==role?{...m,read:true}:m));setDrafts(otherDrafts[id]||{student:'',teacher:''});setPending(otherFiles[id]||{});setMobileList(false);setError('')}
 const draft=drafts[role],attachment=pending[role],full=messages.length>=100;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());urls.current.forEach(u=>URL.revokeObjectURL(u))}},[]);
 useEffect(()=>{if(history.current)history.current.scrollTop=history.current.scrollHeight},[messages,role]);
 function removePending(forRole:Role){const old=pending[forRole];if(old){URL.revokeObjectURL(old.url);urls.current.delete(old.url);totalBytes.current-=old.size}setPending(p=>({...p,[forRole]:undefined}))}
 function addAttachment(blob:Blob,name:string,forRole:Role){
  const previous=pending[forRole];if(blob.size>20*1024*1024||totalBytes.current-(previous?.size||0)+blob.size>50*1024*1024){setError('Use a file under 20 MB. Reset the demo if its 50 MB preview limit is full.');return}
  if(prohibited(name)){setError('Please use a respectful file name.');return}
  if(previous){URL.revokeObjectURL(previous.url);urls.current.delete(previous.url);totalBytes.current-=previous.size}
  const url=URL.createObjectURL(blob);urls.current.add(url);totalBytes.current+=blob.size;setPending(p=>({...p,[forRole]:{url,name,type:blob.type,size:blob.size}}));setError('');
 }
 function selectFile(f?:File){if(!f)return;const ext=f.name.split('.').pop()?.toLowerCase();if(!ext||!['jpg','jpeg','png','webp','gif','mp4','webm','mov','mp3','m4a','ogg','wav','pdf','docx','xlsx','pptx','txt'].includes(ext)){setError('Choose an image, video, audio clip, PDF, Office document or text file.');return}addAttachment(f,f.name,role)}
 function send(text=draft){const body=text.trim();if(full||recording||starting||(!body&&!attachment))return;if(prohibited(body)){setError('Please rephrase your message using respectful language.');return}setMessages(m=>[...m,{id:nextId.current++,role,body,attachment,created:Date.now(),read:false}]);setDrafts(d=>({...d,[role]:''}));setPending(p=>({...p,[role]:undefined}));setError('')}
 function switchRole(next:Role){if(recording||starting)return;if(next==='student'&&chat.student!=='Ahmed'||next==='teacher'&&chat.teacher!=='Mr. Karim')selectChat('math');setRole(next);setMessages(m=>m.map(message=>message.role!==next?{...message,read:true}:message));setError('')}
 async function startRecording(){
  if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('Recording is unavailable in this browser. Attach an audio file instead.');return}
  setStarting(true);setError('');try{const audio=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){audio.getTracks().forEach(t=>t.stop());return}stream.current=audio;
   const mime=['audio/webm','audio/mp4','audio/ogg'].find(t=>MediaRecorder.isTypeSupported(t));const media=new MediaRecorder(audio,mime?{mimeType:mime}:undefined);recorder.current=media;const chunks:Blob[]=[];recordBytes.current=0;const recordingRole=role;
   media.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);recordBytes.current+=e.data.size;if(recordBytes.current>20*1024*1024&&media.state==='recording')media.stop()}};
   media.onstop=()=>{audio.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;if(!alive.current)return;setRecording(false);const blob=new Blob(chunks,{type:media.mimeType||'audio/webm'});if(blob.size)addAttachment(blob,'Voice message.'+(blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm'),recordingRole)};
   media.onerror=()=>{audio.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);if(alive.current){setRecording(false);setError('Recording failed. Try attaching an audio file.')}};
   media.start(250);setSeconds(0);setRecording(true);let elapsed=0;timer.current=setInterval(()=>{elapsed++;setSeconds(elapsed);if(elapsed>=60&&media.state==='recording')media.stop()},1000);
  }catch{stream.current?.getTracks().forEach(t=>t.stop());setError('Microphone access was unavailable or declined. You can attach an audio file instead.')}finally{if(alive.current)setStarting(false)}
 }
 function reset(){if(recording||starting)return;urls.current.forEach(u=>URL.revokeObjectURL(u));urls.current.clear();totalBytes.current=0;setOtherChats({});setOtherDrafts({});setOtherFiles({});setActive('math');setMobileList(false);setPending({});setDrafts({student:'',teacher:''});setMessages(initial());setRole('student');setError('');nextId.current=1}
 function preview(a:Attachment){return <div className="demo-attachment"><FileAttachment file={a} local/></div>}
 return <section className={'chat-demo two-sided-demo '+(mobileList?'demo-list-open':'demo-thread-open')} aria-label="Teacher chat demo">
  <aside className="demo-inbox"><div className="demo-inbox-toolbar"><h2>Chats</h2><button className="icon-button" aria-label="Close teacher chat" onClick={onClose}><ArrowLeft size={21}/></button><details className="demo-account-menu"><summary aria-label="Demo account"><Users size={21}/></summary><p>Local demo · Nothing is sent.</p><div className="demo-role-switch" aria-label="Demo sender">{(['student','teacher'] as Role[]).map(r=><button key={r} aria-pressed={role===r} disabled={recording||starting} onClick={()=>switchRole(r)}>{r==='student'?'Student view':'Teacher view'}</button>)}</div><button onClick={reset} disabled={recording||starting}>Reset demo</button></details></div><div className="demo-inbox-search"><Search size={17}/><input aria-label="Search demo chats" placeholder={role==='student'?'Search teachers':'Search students'} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="demo-chat-list">{chats.filter(c=>(c.teacher+' '+c.student).toLowerCase().includes(query.toLowerCase())).map(c=>{const name=role==='student'?c.teacher:c.student;const last=(c.id===active?messages:otherChats[c.id])?.at(-1);return <button key={c.id} className={'demo-contact '+(active===c.id?'selected':'')} disabled={recording||starting} onClick={()=>selectChat(c.id)}><span className="demo-avatar">{name.charAt(0)}</span><span><b>{name}</b><small>{last?.body||c.subject+' · '+c.className}</small></span></button>})}</div></aside><div className="demo-main">
  <div className="demo-top"><button className="icon-button demo-back" aria-label="Back to demo chats" disabled={recording||starting} onClick={()=>setMobileList(true)}><ArrowLeft size={21}/></button><span className="demo-avatar">{(role==='student'?chat.teacher:chat.student).charAt(0)}</span><div><h3>{role==='student'?chat.teacher:chat.student}</h3><p>{role==='student'?chat.subject:'Class '+chat.className}</p></div><span className="pill amber">DEMO</span><details className="demo-account-menu"><summary aria-label="Demo conversation options"><Users size={21}/></summary><p>Local preview · Nothing is sent.</p><div className="demo-role-switch">{(['student','teacher'] as Role[]).map(r=><button key={r} aria-pressed={role===r} disabled={recording||starting} onClick={()=>switchRole(r)}>{r==='student'?'Student view':'Teacher view'}</button>)}</div><button onClick={reset} disabled={recording||starting}>Reset demo</button></details></div>
  <div className="demo-perspective"><strong>Sending as {names[role]}</strong></div>
  <div ref={history} className="demo-messages" role="log" aria-label="Demo messages" aria-live="polite">{messages.map(m=><div key={m.id} className={'demo-bubble '+(m.role===role?'mine':'')}><small>{names[m.role]}</small>{m.body&&<span dir="auto">{m.body}</span>}{m.attachment&&preview(m.attachment)}<div className="demo-message-meta"><time>{new Date(m.created).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time>{m.role===role&&<span>{m.read?<CheckCheck size={14}/>:<Check size={14}/>} {m.read?'Read in demo':'Sent in demo'}</span>}</div></div>)}</div>

  {attachment&&<div className="demo-pending">{preview(attachment)}<button className="icon-button" aria-label="Remove demo attachment" disabled={recording||starting} onClick={()=>removePending(role)}><X size={18}/></button></div>}
  {error&&<p className="comm-error" role="alert">{error}</p>}
  {recording&&<div className="recording" role="status"><span/>Recording · {seconds}s / 60s<button type="button" onClick={()=>recorder.current?.stop()}><Square size={16}/>Stop & preview</button></div>}
  <form className="demo-composer" onSubmit={e=>{e.preventDefault();send()}}><button type="button" className="icon-button" aria-label="Choose demo emoji" aria-expanded={emojiOpen} onClick={()=>setEmojiOpen(!emojiOpen)}><Smile size={23}/></button>{emojiOpen&&<div className="emoji-picker">{['😊','👍','🙏','🎉','✅','❤️','🤔','👋'].map(emoji=><button type="button" key={emoji} aria-label={'Insert '+emoji} onClick={()=>{setDrafts(d=>({...d,[role]:d[role]+emoji}));setEmojiOpen(false)}}>{emoji}</button>)}</div>}<button type="button" className="icon-button" aria-label="Attach demo file" disabled={recording||starting||full} onClick={()=>file.current?.click()}><Paperclip size={23}/></button><label className="sr-only" htmlFor="demo-message">Try a demo message</label><input id="demo-message" value={draft} maxLength={2000} disabled={full} onChange={e=>setDrafts(d=>({...d,[role]:e.target.value}))} placeholder="Type a message" autoComplete="off"/><button type="button" className="icon-button demo-mic" aria-label="Record demo voice" disabled={starting||full} onClick={()=>recording?recorder.current?.stop():startRecording()}>{recording?<Square size={22}/>:<Mic size={22}/>}</button><button type="submit" className="primary" aria-label="Send demo message" disabled={(!draft.trim()&&!attachment)||full||recording||starting}><Send size={18}/></button></form>
  <div className="demo-tools"><input ref={file} type="file" className="sr-only" tabIndex={-1} aria-label="Choose demo attachment" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime,audio/*,.pdf,.docx,.xlsx,.pptx,.txt" onChange={e=>{selectFile(e.target.files?.[0]);e.target.value=''}}/><button className="text-button" disabled={recording||starting||full} onClick={()=>file.current?.click()}><Paperclip size={17}/>Attach file</button><button className="text-button" disabled={starting||full} onClick={()=>recording?recorder.current?.stop():startRecording()}>{recording?<Square size={17}/>:<Mic size={17}/>} {recording?`Stop · ${seconds}s`:starting?'Opening microphone…':'Record voice'}</button></div>
 </div></section>
}
