'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,ExternalLink,FileText,X} from 'lucide-react';
type SharedFile={id?:string;url?:string;name:string;mime?:string;type?:string;size:number};
export function FileAttachment({file,local=false}:{file:SharedFile;local?:boolean}){
 const source=local?file.url!:'/api/attachments?id='+encodeURIComponent(file.id!);const mime=file.mime||file.type||'';const pdf=mime==='application/pdf'||file.name.toLowerCase().endsWith('.pdf');
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const box=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),alive=useRef(true),abort=useRef<AbortController|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort()}},[]);
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement;box.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const controls=box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],iframe');if(!controls?.length)return;const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===box.current)){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[open]);
 async function download(){if(busy)return;setBusy(true);setError('');let url='';try{abort.current=new AbortController();const response=await fetch(source+(local?'':'&download=1'),{credentials:'same-origin',signal:AbortSignal.any([abort.current.signal,AbortSignal.timeout(60000)])});if(!response.ok){const result:any=await response.json().catch(()=>null);throw Error(result?.error||'This file could not be downloaded. Sign in again or retry.')}if(!local&&response.headers.get('content-type')?.includes('text/html'))throw Error('School sign-in expired. Sign in again to download this file.');const blob=await response.blob();if(!alive.current)return;url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=file.name;document.body.appendChild(anchor);anchor.click();anchor.remove();const retained=url;setTimeout(()=>URL.revokeObjectURL(retained),60000);url=''}catch(e){if(alive.current)setError((e as Error).message||'Download failed. Please retry.')}finally{if(url)URL.revokeObjectURL(url);if(alive.current)setBusy(false)}}
 return <div className="message-attachment shared-file">{mime.startsWith('image/')?<a href={source} target="_blank" rel="noreferrer"><img src={source} alt={file.name} loading="lazy"/></a>:mime.startsWith('video/')?<video controls preload="metadata" src={source}/>:mime.startsWith('audio/')?<audio controls preload="metadata" src={source}/>:null}<div className="shared-file-label"><FileText size={24}/><span><b>{file.name}</b><small>{pdf?'PDF document':mime.startsWith('audio/')?'Audio':mime.startsWith('video/')?'Video':'File'} · {file.size>=1048576?(file.size/1048576).toFixed(1)+' MB':Math.max(1,Math.round(file.size/1024))+' KB'}{local?' · Demo file':''}</small></span></div><div className="shared-file-actions">{pdf?<button type="button" ref={trigger} onClick={()=>setOpen(true)}>Open PDF</button>:<a href={source} target="_blank" rel="noreferrer">Open</a>}<button type="button" onClick={download} disabled={busy}><Download size={16}/>{busy?'Downloading…':'Download'}</button></div>{error&&<p className="file-error" role="alert">{error}</p>}{open&&<div className="document-overlay"><section className="document-viewer" role="dialog" aria-modal="true" aria-label={'PDF: '+file.name} tabIndex={-1} ref={box}><header><span><FileText size={20}/>{file.name}</span><button type="button" onClick={download} disabled={busy}><Download size={18}/>{busy?'Downloading…':'Download'}</button><button type="button" aria-label="Close PDF" onClick={()=>setOpen(false)}><X size={22}/></button></header><iframe title={file.name} src={source}/><footer><span>If your browser cannot preview this PDF, download it to open on your device.</span><a href={source} target="_blank" rel="noreferrer">Open in browser <ExternalLink size={15}/></a></footer>{error&&<p role="alert">{error}</p>}</section></div>}</div>
}
