'use client';
import type {ReactNode} from 'react';
import {ArrowUpRight,CalendarDays,Clock,GraduationCap,MessageSquare,Megaphone,Plus,Ticket,Utensils} from 'lucide-react';
import {homeFocusOptions,normalizeHomeFocus,type HomeFocus} from '@/lib/home-focus';
import type {Item} from '@/lib/board';
type Entry=Item&{expiry?:string;effective?:string;pinned?:boolean;total:number;counts?:number[];mine?:string};
type Props={profile:{nickname:string;grade:number;class_section:string;home_focus?:HomeFocus};onFocusChange:(focus:HomeFocus)=>void;events:Entry[];upcoming:Entry[];polls:Entry[];updates?:Entry[];featured?:Entry;payment?:Entry;meals:{name:string;price:number;soldOut?:boolean}[];sample:boolean;loading:boolean;filter:string;shown:Entry[];onFilter:(filter:string)=>void;onNavigate:(tab:string)=>void;onVoice:(section:string)=>void;onDetail:(entry:Entry)=>void;onDay:(day:string)=>void;renderEvent:(entry:Entry)=>ReactNode;renderPoll:(entry:Entry)=>ReactNode;announcements:ReactNode;attention?:ReactNode};
const format=(value:string,options:Intl.DateTimeFormatOptions)=>new Date(value).toLocaleString('en-GB',{timeZone:'Africa/Cairo',...options});
const dayKey=(value:string)=>new Date(value).toLocaleDateString('en-CA',{timeZone:'Africa/Cairo'});
export function HomeOverview({profile,onFocusChange,events,upcoming,polls,updates=[],featured,payment,meals,sample,loading,renderPoll,onNavigate,onVoice,onDetail,onDay,announcements,attention}:Props){
 const now=new Date(),today=dayKey(now.toISOString());const todayEvents=events.filter(e=>e.start&&e.stage!=='Cancelled'&&dayKey(e.start)<=today&&dayKey(new Date(e.end?Math.max(Date.parse(e.start),Date.parse(e.end)-1):Date.parse(e.start)).toISOString())>=today);
 const current=todayEvents.find(e=>!e.end||Date.parse(e.end)>now.getTime());const lead=current||upcoming.find(e=>e.stage!=='Cancelled'&&e.start&&Date.parse(e.start)>now.getTime());const later=todayEvents.filter(e=>e.id!==current?.id);
 const next=upcoming.filter(e=>e.stage!=='Cancelled'&&e.id!==featured?.id&&e.id!==lead?.id&&!todayEvents.some(t=>t.id===e.id)).slice(0,3);const nextExam=upcoming.find(e=>e.category==='Exam'&&e.stage!=='Cancelled'&&!todayEvents.some(t=>t.id===e.id));const activePolls=polls.filter(p=>Date.parse(p.end||'')>now.getTime());
 const schoolUpdates=updates.filter(i=>(!i.expiry||i.expiry>=today)&&(!i.effective||i.effective<=today)).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));
 function eventRow(e:Entry){return <button className="daily-event" key={e.id} onClick={()=>onDetail(e)}><span className="daily-event-time">{e.category==='Holiday'?'All day':dayKey(e.start!)===today?format(e.start!,{hour:'2-digit',minute:'2-digit'}):format(e.start!,{day:'numeric',month:'short'})}</span><span><b>{e.title}</b><small>{e.category}{e.room?' · '+e.room:''}{e.sample?' · Sample':''}</small></span><ArrowUpRight size={18}/></button>}
 const focus=normalizeHomeFocus(profile.home_focus);
 const availableTrips=events.filter(e=>e.category==='Trip'&&e.stage!=='Cancelled'&&e.start&&Date.parse(e.end||e.start)>now.getTime()).slice(0,4);
 const daySection=<div data-home-section="events" className="daily-main-grid"><section className="daily-today"><div className="daily-section-heading"><h2>{current?'Up next today':lead?'Your next event':'Today'}</h2><button onClick={()=>onDay(today)}>View calendar</button></div>{loading&&!events.length?<p className="daily-empty" role="status">Loading your school day…</p>:lead?<button className="daily-lead" onClick={()=>onDetail(lead)}><span className="daily-lead-date"><small>{format(lead.start!,{month:'short'})}</small><b>{format(lead.start!,{day:'2-digit'})}</b></span><span className="daily-lead-copy"><small>{lead.category}{lead.sample?' · Sample':''}</small><strong>{lead.title}</strong><span>{format(lead.start!,{weekday:'short',hour:'2-digit',minute:'2-digit'})}{lead.room?' · '+lead.room:''}</span></span><span className="daily-lead-action">View details</span></button>:<div className="daily-empty"><CalendarDays size={24}/><h3>No published events today.</h3><p>Your next school updates will appear here.</p></div>}{later.length>0&&<details className="daily-later"><summary>{current?'More today':'Earlier today'} · {later.length} event{later.length===1?'':'s'}</summary><div>{later.slice(0,4).map(eventRow)}{later.length>4&&<button className="daily-text-link" onClick={()=>onDay(today)}>View all {later.length} events</button>}</div></details>}{nextExam&&nextExam.id!==lead?.id&&<button className="daily-next-exam" onClick={()=>onDetail(nextExam)}><GraduationCap size={21}/><span><small>Next assessment</small><b>{nextExam.title}</b></span><time>{format(nextExam.start!,{day:'numeric',month:'short'})}</time></button>}<a className="daily-classroom" href="https://classroom.google.com" target="_blank" rel="noreferrer">Open Google Classroom <ArrowUpRight size={16}/></a></section>
 <aside className="daily-attention"><div className="daily-section-heading"><h2>Keep in mind</h2></div>{attention}{payment&&payment.deadline&&<button className="daily-attention-item deadline" onClick={()=>onDetail(payment)}><Clock size={20}/><span><b>Payment deadline</b><small>{payment.title} · {format(payment.deadline,{day:'numeric',month:'short'})}</small></span></button>}{activePolls.length>0&&<button className="daily-attention-item" onClick={()=>onVoice('Council polls')}><MessageSquare size={20}/><span><b>Open polls</b><small>{activePolls.length} poll{activePolls.length===1?'':'s'} available for your class</small></span></button>}<button className="daily-attention-item" onClick={()=>onVoice('Private suggestions')}><Plus size={20}/><span><b>Share an idea</b><small>Send a suggestion privately</small></span></button><button className="daily-menu-link" onClick={()=>onNavigate('Canteen')}>Today’s canteen menu <ArrowUpRight size={16}/></button></aside></div>;
 const upcomingSection=<section className="daily-upcoming"><div className="daily-section-heading"><h2>Coming up</h2><button onClick={()=>onNavigate('Calendar')}>Full calendar</button></div>{next.length?<div>{next.map(eventRow)}</div>:<p className="daily-empty">No other upcoming events published for your class.</p>}</section>;
 const announcementSection=<section data-home-section="announcements" className="daily-school-updates" id="home-announcements"><div className="daily-section-heading"><h2><Megaphone size={21}/>School announcements</h2><span className="pill amber">For your school day</span></div>{schoolUpdates.length?<div className="home-announcement-list">{schoolUpdates.slice(0,4).map(i=><details key={i.id} className="home-announcement"><summary><span><small>{i.pinned?'Pinned announcement':'School update'}{i.effective?' · '+format(i.effective,{day:'numeric',month:'short'}):''}</small><b>{i.title}</b></span><Plus size={18}/></summary><p dir="auto">{i.description}</p></details>)}</div>:<><p className="home-empty-note">No new announcements for your class. Check back for school updates.</p>{announcements}</>}{focus==='balanced'&&featured&&<button className="daily-trip-row" onClick={()=>onDetail(featured)}>{featured.id==='trip-rayan'?<img src="/images/wadi-el-rayan.jpg" alt="Wadi El Rayan lake" loading="lazy"/>:<span className="daily-trip-icon"><Ticket size={25}/></span>}<span><small>School trip{featured.sample?' · Sample':''}</small><b>{featured.title}</b><span>{format(featured.start!,{day:'numeric',month:'long'})}{featured.cost!==undefined?' · '+featured.cost+' EGP':''}</span></span><ArrowUpRight size={20}/></button>}</section>;
 const pollSection=<section data-home-section="polls" className="home-polls"><div className="daily-section-heading"><div><h2>Your voice matters</h2><p>Take part in the decisions open to your class.</p></div><button onClick={()=>onVoice('Council polls')}>View all polls</button></div>{activePolls.length?<div className="home-poll-grid">{activePolls.slice(0,2).map(renderPoll)}</div>:<div className="home-empty-note"><MessageSquare size={22}/><span>No open polls right now. You can still share an idea with the High Board.</span><button className="text-button" onClick={()=>onVoice('Private suggestions')}>Share an idea</button></div>}</section>;
 const tripSection=<section className="home-trips" data-home-section="trips"><div className="daily-section-heading"><h2><Ticket size={21}/>School trips</h2><button onClick={()=>onNavigate('Calendar')}>View calendar</button></div>{availableTrips.length?<div>{availableTrips.map(trip=><button className="daily-trip-row" key={trip.id} onClick={()=>onDetail(trip)}><span className="daily-trip-icon"><Ticket size={25}/></span><span><small>School trip{trip.sample?' · Sample':''}</small><b>{trip.title}</b><span>{format(trip.start!,{day:'numeric',month:'long'})}{trip.cost!==undefined?' · '+trip.cost+' EGP':''}</span></span><ArrowUpRight size={20}/></button>)}</div>:<p className="home-empty-note">No upcoming trip recommendations right now. Find all trips, including ones you declined, in Calendar.</p>}</section>;
 const focusedSection={trips:tripSection,announcements:announcementSection,polls:pollSection,events:daySection,balanced:null}[focus];
 return <div className="home-dashboard daily-dashboard" id="student-board"><header className="daily-heading"><div><p>{format(now.toISOString(),{weekday:'long',day:'numeric',month:'long'})}</p><h1>{profile.nickname?`Good to see you, ${profile.nickname.trim().split(/\s+/)[0]}.`:'Your school day.'}</h1></div><button className="daily-chat-action" onClick={()=>onVoice('Teacher chat')}><MessageSquare size={19}/>Teacher chat</button></header>{sample&&<div className="daily-preview">Preview · Events and menu include sample data.</div>}
 <label className="home-focus-control">Home focus<select value={focus} onChange={e=>onFocusChange(normalizeHomeFocus(e.target.value))}>{homeFocusOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><nav className="daily-quick" aria-label="Homepage shortcuts"><button onClick={()=>onNavigate('Calendar')}><CalendarDays size={23}/><span>Calendar</span></button><button onClick={()=>onVoice('Teacher chat')}><MessageSquare size={23}/><span>Messages</span></button><button onClick={()=>onVoice('Private suggestions')}><Plus size={23}/><span>Your voice</span></button><button onClick={()=>onNavigate('Canteen')}><Utensils size={23}/><span>Canteen</span></button></nav>
 <div className="home-brief" aria-label="Your school at a glance"><button onClick={()=>onNavigate('Calendar')}><CalendarDays size={21}/><span><b>{todayEvents.length}</b>Today’s events</span></button><button onClick={()=>onVoice('Council polls')}><MessageSquare size={21}/><span><b>{activePolls.length}</b>Open polls</span></button><a href="#home-announcements"><Megaphone size={21}/><span><b>{schoolUpdates.length}</b>School announcements</span></a></div>
 {focus!=='balanced'&&<p className="home-focus-status" role="status">{homeFocusOptions.find(option=>option.value===focus)?.label} appears first. All school content stays available below.</p>}{focus==='balanced'?<>{daySection}{upcomingSection}{announcementSection}{pollSection}</>:<>{focusedSection}{focus!=='events'&&daySection}{upcomingSection}{focus!=='announcements'&&announcementSection}{focus!=='trips'&&tripSection}{focus!=='polls'&&pollSection}</>}{meals.length>0&&<section className="home-lunch-preview"><Utensils size={23}/><div><b>On the menu today</b><p>{meals.slice(0,3).map(m=>m.name+(m.soldOut?' · sold out':' · '+m.price+' EGP')).join(' / ')}</p></div><button className="secondary" onClick={()=>onNavigate('Canteen')}>See menu</button></section>}</div>
}
