'use client';
import type {ReactNode} from 'react';
import {ArrowUpRight,CalendarDays,Clock,GraduationCap,MessageSquare,Plus,Ticket,Utensils} from 'lucide-react';
import type {Item} from '@/lib/board';
type Entry=Item&{total:number;counts?:number[];mine?:string};
type Props={profile:{nickname:string;grade:number;class_section:string};events:Entry[];upcoming:Entry[];polls:Entry[];featured?:Entry;payment?:Entry;meals:{name:string;price:number;soldOut?:boolean}[];sample:boolean;loading:boolean;filter:string;shown:Entry[];onFilter:(filter:string)=>void;onNavigate:(tab:string)=>void;onVoice:(section:string)=>void;onDetail:(entry:Entry)=>void;onDay:(day:string)=>void;renderEvent:(entry:Entry)=>ReactNode;renderPoll:(entry:Entry)=>ReactNode;announcements:ReactNode;attention?:ReactNode};
const format=(value:string,options:Intl.DateTimeFormatOptions)=>new Date(value).toLocaleString('en-GB',{timeZone:'Africa/Cairo',...options});
const dayKey=(value:string)=>new Date(value).toLocaleDateString('en-CA',{timeZone:'Africa/Cairo'});
export function HomeOverview({profile,events,upcoming,polls,featured,payment,sample,loading,onNavigate,onVoice,onDetail,onDay,announcements,attention}:Props){
 const now=new Date(),today=dayKey(now.toISOString());const todayEvents=events.filter(e=>e.start&&e.stage!=='Cancelled'&&dayKey(e.start)<=today&&dayKey(new Date(e.end?Math.max(Date.parse(e.start),Date.parse(e.end)-1):Date.parse(e.start)).toISOString())>=today);
 const current=todayEvents.find(e=>!e.end||Date.parse(e.end)>now.getTime());const lead=current||upcoming.find(e=>e.stage!=='Cancelled'&&e.start&&Date.parse(e.start)>now.getTime());const later=todayEvents.filter(e=>e.id!==current?.id);
 const next=upcoming.filter(e=>e.stage!=='Cancelled'&&e.id!==featured?.id&&e.id!==lead?.id&&!todayEvents.some(t=>t.id===e.id)).slice(0,3);const nextExam=upcoming.find(e=>e.category==='Exam'&&e.stage!=='Cancelled'&&!todayEvents.some(t=>t.id===e.id));const activePolls=polls.filter(p=>Date.parse(p.end||'')>now.getTime());
 function eventRow(e:Entry){return <button className="daily-event" key={e.id} onClick={()=>onDetail(e)}><span className="daily-event-time">{e.category==='Holiday'?'All day':dayKey(e.start!)===today?format(e.start!,{hour:'2-digit',minute:'2-digit'}):format(e.start!,{day:'numeric',month:'short'})}</span><span><b>{e.title}</b><small>{e.category}{e.room?' · '+e.room:''}{e.sample?' · Sample':''}</small></span><ArrowUpRight size={18}/></button>}
 return <div className="home-dashboard daily-dashboard" id="student-board"><header className="daily-heading"><div><p>{format(now.toISOString(),{weekday:'long',day:'numeric',month:'long'})}</p><h1>{profile.nickname?`Good to see you, ${profile.nickname.trim().split(/\s+/)[0]}.`:'Your school day.'}</h1></div><button className="daily-chat-action" onClick={()=>onVoice('Teacher chat')}><MessageSquare size={19}/>Teacher chat</button></header>{sample&&<div className="daily-preview">Preview · Events and menu include sample data.</div>}
 <nav className="daily-quick" aria-label="Homepage shortcuts"><button onClick={()=>onNavigate('Calendar')}><CalendarDays size={23}/><span>Calendar</span></button><button onClick={()=>onVoice('Teacher chat')}><MessageSquare size={23}/><span>Messages</span></button><button onClick={()=>onVoice('Private suggestions')}><Plus size={23}/><span>Your voice</span></button><button onClick={()=>onNavigate('Canteen')}><Utensils size={23}/><span>Canteen</span></button></nav>
 <div className="daily-main-grid"><section className="daily-today"><div className="daily-section-heading"><h2>{current?'Up next today':lead?'Your next event':'Today'}</h2><button onClick={()=>onDay(today)}>View calendar</button></div>{loading&&!events.length?<p className="daily-empty" role="status">Loading your school day…</p>:lead?<button className="daily-lead" onClick={()=>onDetail(lead)}><span className="daily-lead-date"><small>{format(lead.start!,{month:'short'})}</small><b>{format(lead.start!,{day:'2-digit'})}</b></span><span className="daily-lead-copy"><small>{lead.category}{lead.sample?' · Sample':''}</small><strong>{lead.title}</strong><span>{format(lead.start!,{weekday:'short',hour:'2-digit',minute:'2-digit'})}{lead.room?' · '+lead.room:''}</span></span><span className="daily-lead-action">View details</span></button>:<div className="daily-empty"><CalendarDays size={24}/><h3>No published events today.</h3><p>Your next school updates will appear here.</p></div>}{later.length>0&&<details className="daily-later"><summary>{current?'More today':'Earlier today'} · {later.length} event{later.length===1?'':'s'}</summary><div>{later.slice(0,4).map(eventRow)}{later.length>4&&<button className="daily-text-link" onClick={()=>onDay(today)}>View all {later.length} events</button>}</div></details>}{nextExam&&nextExam.id!==lead?.id&&<button className="daily-next-exam" onClick={()=>onDetail(nextExam)}><GraduationCap size={21}/><span><small>Next assessment</small><b>{nextExam.title}</b></span><time>{format(nextExam.start!,{day:'numeric',month:'short'})}</time></button>}<a className="daily-classroom" href="https://classroom.google.com" target="_blank" rel="noreferrer">Open Google Classroom <ArrowUpRight size={16}/></a></section>
 <aside className="daily-attention"><div className="daily-section-heading"><h2>Keep in mind</h2></div>{attention}{payment&&payment.deadline&&<button className="daily-attention-item deadline" onClick={()=>onDetail(payment)}><Clock size={20}/><span><b>Payment deadline</b><small>{payment.title} · {format(payment.deadline,{day:'numeric',month:'short'})}</small></span></button>}{activePolls.length>0&&<button className="daily-attention-item" onClick={()=>onVoice('Council polls')}><MessageSquare size={20}/><span><b>Open polls</b><small>{activePolls.length} poll{activePolls.length===1?'':'s'} available for your class</small></span></button>}<button className="daily-attention-item" onClick={()=>onVoice('Private suggestions')}><Plus size={20}/><span><b>Share an idea</b><small>Send a suggestion privately</small></span></button><button className="daily-menu-link" onClick={()=>onNavigate('Canteen')}>Today’s canteen menu <ArrowUpRight size={16}/></button></aside></div>
 <section className="daily-upcoming"><div className="daily-section-heading"><h2>Coming up</h2><button onClick={()=>onNavigate('Calendar')}>Full calendar</button></div>{next.length?<div>{next.map(eventRow)}</div>:<p className="daily-empty">No other upcoming events published for your class.</p>}</section><section className="daily-school-updates"><div className="daily-section-heading"><h2>School updates</h2></div>{announcements}{featured&&<button className="daily-trip-row" onClick={()=>onDetail(featured)}>{featured.id==='trip-rayan'?<img src="/images/wadi-el-rayan.jpg" alt="Wadi El Rayan lake" loading="lazy"/>:<span className="daily-trip-icon"><Ticket size={25}/></span>}<span><small>School trip{featured.sample?' · Sample':''}</small><b>{featured.title}</b><span>{format(featured.start!,{day:'numeric',month:'long'})}{featured.cost!==undefined?' · '+featured.cost+' EGP':''}</span></span><ArrowUpRight size={20}/></button>}</section></div>
}
