'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Contact={id:string;name:string;role:string;email?:string};
type Question={id:string;contact?:string;trip?:string;name?:string;class_name?:string;body:string;answer:string;created:number};
async function request(url:string,body?:object){const r=await fetch(url,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)}),j=await r.json() as {error?:string;contacts:Contact[];candidates:Contact[];questions:Question[];canAsk:boolean};if(!r.ok)throw Error(j.error||'Unable to load trip questions.');return j}
export function TripQuestions({trip,onSignIn}:{trip:string;onSignIn:()=>void}){
 const [data,setData]=useState<{contacts:Contact[];questions:Question[];canAsk:boolean}|null>(null),[contact,setContact]=useState(''),[body,setBody]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[signedOut,setSignedOut]=useState(false);
 const generation=useRef(0);
 const load=useCallback(async()=>{const seq=++generation.current;try{const j=await request('/api/trip-questions?trip='+encodeURIComponent(trip));if(seq!==generation.current)return;setData(j);setContact(old=>j.contacts.some((c:Contact)=>c.id===old)?old:j.contacts[0]?.id||'');setSignedOut(false);setError('')}catch(e){if(seq!==generation.current)return;setData(null);const message=(e as Error).message;setSignedOut(message==='School sign-in required.');setError(message)}},[trip]);
 useEffect(()=>{load();const t=setInterval(()=>{if(!document.hidden)load()},20000);return()=>{clearInterval(t);generation.current++}},[load]);
 return <section className="trip-questions" aria-label="Private trip questions"><h3>Questions about this trip?</h3><p>Your question goes only to the contact you choose. Check back here for their reply.</p>{signedOut?<button className="secondary" onClick={onSignIn}>Sign in to ask a question</button>:error&&<p role="alert" className="comm-error">{error}</p>}{data&&!data.contacts.length&&<p>No question contact has been assigned yet. Please ask the school office.</p>}{data?.contacts.length? <><p className="trip-contact-names">Trip contacts: {data.contacts.map(c=>c.name+(c.role==='council'?' (High Board helper)':'')).join(', ')}</p>{data.canAsk?<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{await request('/api/trip-questions',{action:'ask',trip,contact,body});setBody('');setNotice('Question sent privately.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Send to<select value={contact} onChange={e=>setContact(e.target.value)}>{data.contacts.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Your question<textarea required maxLength={1000} rows={3} value={body} onChange={e=>setBody(e.target.value)} placeholder="For example: What should I bring?"/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Send question'}</button></form>:<p>New questions are closed for this trip.</p>}{notice&&<p role="status" className="trip-response-notice">{notice}</p>}{data.questions.map(q=><article className="trip-question-card" key={q.id}><small>To {data.contacts.find(c=>c.id===q.contact)?.name}</small><p dir="auto">{q.body}</p>{q.answer?<p dir="auto"><b>Reply:</b> {q.answer}</p>:<small>Awaiting a reply</small>}</article>)}</>:null}</section>
}
export function TripContactEditor({trip}:{trip:string}){
 const [data,setData]=useState<{contacts:Contact[];candidates:Contact[]}|null>(null),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setData(null);setError('');setNotice('');request('/api/trip-questions?manage=1&trip='+encodeURIComponent(trip)).then(j=>{if(active){setData(j);setSelected(j.contacts.map((c:Contact)=>c.email!))}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[trip]);
 return <details className="trip-questions"><summary>Assign trip question contacts</summary><p>Choose up to four active teachers, staff members or High Board helpers. Each receives only questions addressed to them. Removed contacts lose access to their trip questions.</p>{error&&<p role="alert" className="comm-error">{error}</p>}{data&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setNotice('');setError('');try{await request('/api/trip-questions',{action:'assign',trip,contacts:selected});setNotice('Trip contacts saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset><legend>Question contacts</legend><div className="trip-contact-picker">{data.candidates.map(c=><label key={c.email}><input type="checkbox" checked={selected.includes(c.email!)} disabled={busy||selected.length>=4&&!selected.includes(c.email!)} onChange={e=>setSelected(old=>e.target.checked?[...old,c.email!]:old.filter(x=>x!==c.email))}/>{c.name} <small>{c.role==='council'?'High Board helper':c.role}</small></label>)}</div></fieldset><button className="secondary" disabled={busy}>{busy?'Saving…':'Save contacts'}</button></form>}{notice&&<p role="status">{notice}</p>}</details>
}
export function TripQuestionInbox(){
 const [questions,setQuestions]=useState<Question[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[filter,setFilter]=useState('pending');
 const load=useCallback(async()=>{try{const j=await request('/api/trip-questions?inbox=1');setQuestions(j.questions);setError('');setLoaded(true)}catch(e){setQuestions([]);setError((e as Error).message)}},[]);
 useEffect(()=>{load();const t=setInterval(()=>{if(!document.hidden)load()},20000);return()=>clearInterval(t)},[load]);
 const shown=questions.filter(q=>filter==='all'||!q.answer);
 return <section className="panel trip-questions" aria-label="Assigned trip questions"><div className="section-title"><h3>Trip questions for you {questions.filter(q=>!q.answer).length>0&&'· '+questions.filter(q=>!q.answer).length+' awaiting reply'}</h3><button className="secondary" onClick={load}>Refresh</button></div><p>Your 200 most recent private questions as a designated trip contact.</p><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Awaiting reply</option><option value="all">All questions</option></select></label>{error&&<p role="alert" className="comm-error">{error}</p>}{loaded&&!shown.length&&<p>No questions in this view.</p>}{shown.map(q=><TripAnswer key={q.id} question={q} onSaved={load}/>)}</section>
}
function TripAnswer({question:q,onSaved}:{question:Question;onSaved:()=>void}){const [answer,setAnswer]=useState(q.answer),[busy,setBusy]=useState(false),[error,setError]=useState('');return <article className="trip-question-card"><h4>{q.trip}</h4><small>{q.name} · Class {q.class_name}</small><p dir="auto">{q.body}</p>{q.answer?<p dir="auto"><b>Your reply:</b> {q.answer}</p>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await request('/api/trip-questions',{action:'reply',id:q.id,answer});onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Private reply<textarea value={answer} onChange={e=>setAnswer(e.target.value)} required maxLength={1000} rows={3}/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Send reply'}</button></form>}{error&&<p role="alert" className="comm-error">{error}</p>}</article>}
