'use client';
import {useState} from 'react';
import {Check,Ticket,X} from 'lucide-react';
import type {Item} from '@/lib/board';
import type {TripResponse} from '@/lib/trip-client';
export function TripInterest({trip,response,onSaved,onSignIn}:{trip:Item;response?:TripResponse;onSaved:(trip:string,response:TripResponse)=>void;onSignIn:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[signIn,setSignIn]=useState(false);
 const closed=trip.stage==='Cancelled'||!trip.start||Date.parse(trip.start)<=Date.now();
 async function choose(choice:TripResponse['choice']){if(busy)return;setBusy(true);setError('');setNotice('');setSignIn(false);try{const r=await fetch('/api/trips',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip:trip.id,choice}),signal:AbortSignal.timeout(15000)}),j:any=await r.json();if(!r.ok){setSignIn(r.status===401);throw Error(j.error||'Unable to save your response.');}onSaved(trip.id,{choice:j.choice,updated:j.updated});setNotice(choice==='interested'?'Staff can now see your name and class for payment collection.':'Trip recommendation hidden. You can change your mind from the calendar.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="trip-interest" aria-label="Your trip response"><div className="trip-interest-heading"><Ticket size={21}/><div><h3>Would you like to go?</h3><p>{trip.sample?'Sample trip · Responses open after staff publish a real trip.':closed?trip.stage==='Cancelled'?'This trip is cancelled.':'Responses have closed.':response?.choice==='interested'?'You want to participate.':response?.choice==='declined'?'You declined. Changed your mind?':'Let staff know whether to visit your class for payment.'}</p></div></div><div className="trip-interest-actions"><button type="button" className={response?.choice==='interested'?'primary':'secondary'} aria-pressed={response?.choice==='interested'} disabled={busy||closed||trip.sample} onClick={()=>choose('interested')}><Check size={17}/>{busy?'Saving…':'I want to go'}</button><button type="button" className={response?.choice==='declined'?'trip-declined':'secondary'} aria-pressed={response?.choice==='declined'} disabled={busy||closed||trip.sample} onClick={()=>choose('declined')}><X size={17}/>I do not want to go</button></div><p className="trip-interest-note">This records interest. Staff confirm payment, permission and your place separately. You can change your response here until the trip starts.</p>{notice&&<p className="trip-response-notice" role="status">{notice}</p>}{error&&<p className="comm-error" role="alert">{error}</p>}{signIn&&<button type="button" className="primary" onClick={onSignIn}>School sign-in</button>}</section>
}
