'use client';
import {useCallback,useEffect,useState} from 'react';
import {RefreshCw,Ticket,Users} from 'lucide-react';
type Student={name:string;class_name:string;updated:number};
type CollectionTrip={id:string;title:string;start?:string;stage:string;cost?:number;deadline?:string;students:Student[];total:number};
export function TripCollection(){const [trips,setTrips]=useState<CollectionTrip[]>([]),[selected,setSelected]=useState(''),[className,setClassName]=useState('All'),[query,setQuery]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const r=await fetch('/api/trips?manage=1',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setTrips(j.trips||[]);setSelected(old=>old&&(j.trips||[]).some((t:CollectionTrip)=>t.id===old)?old:j.trips?.[0]?.id||'');setError('');setLoaded(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[]);
 useEffect(()=>{load();const t=setInterval(()=>{if(!document.hidden)load()},20000);return()=>clearInterval(t)},[load]);const trip=trips.find(t=>t.id===selected);const students=(trip?.students||[]).filter(s=>(className==='All'||s.class_name===className)&&s.name.toLowerCase().includes(query.toLowerCase()));const classes=[...new Set((trip?.students||[]).map(s=>s.class_name))].sort();
 return <section className="panel trip-collection" aria-label="Trip payment collection"><div className="section-title"><h3><Ticket size={20}/>Trip interest &amp; collection</h3><button type="button" className="secondary" onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</button></div><p>Students who currently want to go, grouped by their school-assigned class.</p>{error&&<p className="comm-error" role="alert">{error}</p>}{!loaded&&!error&&<p role="status">Loading trip responses…</p>}{loaded&&!trips.length&&<p>No published trips yet. Sample trips do not collect responses.</p>}{trips.length>0&&<><div className="trip-collection-filters"><label>Trip<select value={selected} onChange={e=>{setSelected(e.target.value);setClassName('All');setQuery('')}}>{trips.map(t=><option value={t.id} key={t.id}>{t.title}{t.stage!=='Published'?' · '+t.stage:''}</option>)}</select></label><label>Class<select value={className} onChange={e=>setClassName(e.target.value)}><option>All</option>{classes.map(c=><option key={c}>{c}</option>)}</select></label><label>Find a student<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names…"/></label></div>{trip&&<><div className="trip-collection-summary"><span><Users size={18}/>{trip.total} interested student{trip.total===1?'':'s'}</span>{trip.cost!==undefined&&<span>{trip.cost} EGP per student</span>}{trip.deadline&&<span>Pay by {new Date(trip.deadline).toLocaleString('en-GB',{timeZone:'Africa/Cairo'})}</span>}</div>{trip.stage!=='Published'&&<p className="comm-error">{trip.stage} trip · Do not collect payment from this list.</p>}<div className="table-wrap"><table><caption className="sr-only">Interested students for {trip.title}</caption><thead><tr><th>Class</th><th>Student</th><th>Response updated</th></tr></thead><tbody>{students.map((s,i)=><tr key={s.class_name+'|'+s.name+'|'+i}><td><b>{s.class_name}</b></td><td>{s.name}</td><td>{new Date(s.updated).toLocaleString('en-GB',{timeZone:'Africa/Cairo',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</td></tr>)}</tbody></table></div>{!students.length&&<p>No interested students match this view.</p>}<p className="trip-interest-note">A changed response replaces the previous choice. Declined students leave this collection list. Interest is not confirmation of payment or guardian permission.</p></>}</>}</section>
}
