'use client';
import {useCallback,useEffect,useState} from 'react';
import {Clock,CalendarDays,Megaphone,Shield,Plus} from 'lucide-react';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const labels:Record<string,string>={student:'Student',teacher:'Teacher',council:'High Board',staff:'School staff',administrator:'Administrator'};
export function Workspace({onMessages}:{onMessages:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[kind,setKind]=useState('announcement'),[day,setDay]=useState(()=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Cairo',weekday:'short'}).format(new Date()))),[now,setNow]=useState(new Date());
 const load=useCallback(async()=>{try{const r=await fetch('/api/workspace',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{load();const t=setInterval(()=>{setNow(new Date());if(!document.hidden)load()},60000);return()=>clearInterval(t)},[load]);
 async function send(body:any){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j:any=await r.json();if(!r.ok)throw Error(j.error);setNotice(j.stage?'Saved · '+j.stage:'Changes saved.');await load();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 if(!data)return <div className="panel" role="status">{error||'Loading your workspace…'}<button className="secondary" onClick={load}>Retry</button></div>;
 if(!data.person)return <section className="panel workspace-signin"><Shield size={30}/><h2>Your school workspace</h2><p>Sign in to see your assigned account, class updates and publishing tools.</p><button className="primary" onClick={onMessages}>School sign-in</button></section>;
 const teacher=['teacher','staff','administrator'].includes(data.person.role),council=data.person.role==='council',time=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Cairo',hour:'2-digit',minute:'2-digit',hour12:false}).format(now),today=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Cairo',weekday:'short'}).format(now));
 const sessions=data.schedule.filter((s:any)=>s.day===day).sort((a:any,b:any)=>a.start.localeCompare(b.start));const current=data.schedule.find((s:any)=>s.day===today&&s.start<=time&&s.end>time);const next=data.schedule.filter((s:any)=>s.day===today&&s.start>time).sort((a:any,b:any)=>a.start.localeCompare(b.start))[0];
 return <section className="workspace"><div className="view-heading"><div><span className="eyebrow">{labels[data.person.role]} WORKSPACE</span><h2>{data.person.name}</h2><p>{teacher?'Your day, classes and school updates.':council?'Your student life and High Board responsibilities.':'Your class updates in one place.'}</p></div><button className="secondary" onClick={onMessages}>Messages</button></div>{error&&<p className="comm-error" role="alert">{error}</p>}{notice&&<p className="comm-notice" role="status">{notice}</p>}
 {teacher&&<><div className="workspace-stats"><article className="panel"><Clock/><small>Right now · Cairo</small><h3>{current?.title||'No scheduled session'}</h3><p>{current?`${current.start}–${current.end} · ${current.class_name||current.kind}`:'Your timetable is private to your account.'}</p></article><article className="panel"><CalendarDays/><small>Up next today</small><h3>{next?.title||'No upcoming sessions'}</h3><p>{next?`${next.start} · ${next.class_name||next.kind} · ${next.room||''}`:'Add your sessions and breaks below.'}</p></article></div><section className="panel"><div className="section-title"><h3>Weekly timetable</h3><label>Day<select value={day} onChange={e=>setDay(Number(e.target.value))}>{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label></div>{sessions.length?sessions.map((s:any)=><article className="workspace-session" key={s.id}><b>{s.start}–{s.end}</b><span>{s.title}<small>{s.kind} {s.class_name} {s.room}</small></span><button className="text-button" disabled={busy} onClick={()=>send({action:'removeSchedule',id:s.id})} aria-label={'Remove '+s.title}>Remove</button></article>):<p>No sessions saved for {days[day]}.</p>}<details><summary><Plus size={16}/> Add a session or break</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await send({action:'schedule',day,...Object.fromEntries(new FormData(form))}))form.reset()}}><label>Title<input name="title" required maxLength={120}/></label><div className="two-fields"><label>Type<select name="kind"><option>Session</option><option>Break</option></select></label><label>Class<select name="class_name"><option value="">No class / break</option>{data.person.classes.map((c:string)=><option key={c}>{c}</option>)}</select></label></div><div className="two-fields"><label>Start<input name="start" type="time" required/></label><label>End<input name="end" type="time" required/></label></div><label>Room<input name="room" maxLength={80}/></label><button className="primary" disabled={busy}>Save session</button></form></details></section></>}
 <div className="workspace-columns">{data.canManage&&<section className="panel"><h3><Megaphone size={19}/>Create an update</h3><form onSubmit={async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),b:any=Object.fromEntries(fd);b.action='publish';b.kind=kind;b.classes=fd.getAll('classes');b.grades=fd.getAll('grades').map(Number);b.global=fd.get('global')==='on';for(const key of ['start','end'])if(b[key])b[key]=new Date(b[key]).toISOString();if(await send(b))f.reset()}}><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="announcement">Announcement</option><option value="event">Class event / trip</option>{data.person.role!=='teacher'&&<option value="poll">Poll</option>}</select></label><label>Title<input name="title" maxLength={160} required/></label><label>Details<textarea name="description" rows={4} maxLength={2000} required/></label><fieldset><legend>Who should see this?</legend>{data.person.role!=='teacher'&&<><label className="check"><input name="global" type="checkbox"/>All grades</label><div className="workspace-audiences">{Array.from({length:12},(_,i)=>i+1).map(g=><label key={g}><input type="checkbox" name="grades" value={g}/>Grade {g}</label>)}</div></>}<div className="workspace-audiences">{data.person.classes.map((c:string)=><label key={c}><input type="checkbox" name="classes" value={c}/>{c}</label>)}</div></fieldset>{kind==='event'&&<><label>Event category<select name="category"><option>Class Event</option><option>Trip</option></select></label><label>Starts<input type="datetime-local" name="start" required/></label><label>Ends<input type="datetime-local" name="end" required/></label><label>Room / meeting point<input name="room" maxLength={100}/></label></>}{kind==='poll'&&<><label>Choices · one per line<textarea name="options" rows={4} required/></label><label>Voting closes<input type="datetime-local" name="end" required/></label></>}<label>Save as<select name="stage"><option value="Published">{council?'Submit for staff approval':'Publish'}</option><option>Draft</option></select></label>{council&&<p className="comm-note">Staff approve High Board drafts before they appear on the school board.</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save update'}</button></form></section>}
 <section className="panel"><h3>Updates for you</h3>{!data.items.length&&<p>No updates for your account yet.</p>}{data.items.map((i:any)=><article className="workspace-post" key={i.id}><span className="pill">{i.kind} · {i.stage||'Published'}</span><h4>{i.title}</h4><p dir="auto">{i.description}</p><small>{i.author||'High Board'} · {i.audience.is_global?'All grades':[...i.audience.target_grades.map((g:number)=>'Grade '+g),...i.audience.target_classes].join(', ')}</small>{i.start&&<p>{new Date(i.start).toLocaleString('en-GB',{timeZone:'Africa/Cairo'})} · Cairo</p>}{['Draft','Pending approval'].includes(i.stage)&&(i.mine||['staff','administrator'].includes(data.person.role))&&<button className="primary" disabled={busy} onClick={()=>send({action:'release',id:i.id})}>{council?'Submit for approval':'Publish'}</button>}{(i.mine||data.person.role==='administrator')&&i.stage!=='Archived'&&<button className="text-button" disabled={busy} onClick={()=>send({action:'archive',id:i.id})}>Archive</button>}</article>)}</section></div></section>
}
