export type Audience={is_global:boolean;target_grades:number[];target_classes:string[];excluded_classes:string[]};
export type Item={id:string;kind:string;title:string;category?:string;description?:string;start?:string;end?:string;cost?:number;deadline?:string;transport?:string;food?:string;notes?:string;room?:string;duration?:number;audience:Audience;options?:string[];multi?:boolean;status?:string;sample?:boolean;stage?:string;menu_date?:string;verified?:boolean};
export const globalAudience:Audience={is_global:true,target_grades:[],target_classes:[],excluded_classes:[]};
export function visible(a:Audience,g:number,c:string){return (a.is_global||a.target_grades.includes(g)||a.target_classes.includes(c))&&!a.excluded_classes.includes(c)}
export const seed:Item[]=[
{id:'trip-rayan',kind:'event',category:'Trip',title:'A day beyond the classroom.',description:'Wadi El Rayan • Sandboarding, outdoor games and a little adventure.',start:'2026-11-15T07:00:00+02:00',end:'2026-11-15T18:00:00+02:00',cost:500,deadline:'2026-11-08T23:59:59+02:00',transport:'Main gate · 7:00 AM · Air-conditioned buses',food:'Breakfast box & BBQ lunch',notes:'Sports attire, closed shoes, water bottle. Stay with your group and follow staff instructions. Pocket money limit: 200 EGP.',audience:{is_global:false,target_grades:[7,8,9],target_classes:[],excluded_classes:['8C']},sample:true},
{id:'sports',kind:'event',category:'Class Event',title:'Sports Day. Bring your team spirit.',description:'House competitions, relay races and a school-wide celebration.',start:'2026-10-22T09:00:00+03:00',end:'2026-10-22T14:00:00+03:00',audience:globalAudience,sample:true},
{id:'party-8a',kind:'event',category:'Class Event',title:'8A dish party',description:'Bring a favourite dish to share. Please label ingredients and allergens.',start:'2026-10-12T12:30:00+03:00',end:'2026-10-12T13:30:00+03:00',audience:{...globalAudience,is_global:false,target_classes:['8A']},sample:true},
{id:'holiday',kind:'event',category:'Holiday',title:'Armed Forces Day',description:'School closed. Enjoy the break.',start:'2026-10-06T00:00:00+03:00',end:'2026-10-07T00:00:00+03:00',audience:globalAudience,sample:true},
{id:'exam-8',kind:'event',category:'Exam',title:'Mathematics',description:'Term assessment',start:'2026-10-19T09:00:00+03:00',end:'2026-10-19T10:30:00+03:00',room:'Hall B',duration:90,audience:{...globalAudience,is_global:false,target_grades:[8]},sample:true},
{id:'exam-eng',kind:'event',category:'Exam',title:'English language',description:'Term assessment',start:'2026-10-21T09:00:00+03:00',end:'2026-10-21T10:00:00+03:00',room:'Hall A',duration:60,audience:{...globalAudience,is_global:false,target_grades:[8]},sample:true},
{id:'menu-vote',kind:'poll',title:'What should join the canteen menu?',description:'Your next lunch favourite starts here.',options:['Fresh fruit smoothies','Warm paninis','Yogurt & granola'],end:'2026-10-30T23:59:59+02:00',audience:globalAudience,sample:true},
{id:'theme-7e',kind:'poll',title:'7E: choose your class party theme',options:['Retro','Tropical','Sports'],end:'2026-10-18T23:59:59+03:00',audience:{...globalAudience,is_global:false,target_classes:['7E']},sample:true},
{id:'idea-1',kind:'idea',title:'More shaded seating in the courtyard',status:'Under Review',audience:globalAudience,sample:true},
{id:'idea-2',kind:'idea',title:'A student-led charity sports tournament',status:'Approved',audience:globalAudience,sample:true},
{id:'menu',kind:'menu',title:'Today’s menu',description:JSON.stringify([{name:'Grilled chicken wrap',price:65,tags:'High protein'},{name:'Cheese panini',price:45,tags:'Vegetarian · Dairy'},{name:'Fresh fruit cup',price:30,tags:'Vegan'},{name:'Water',price:10,tags:'500 ml'}]),audience:globalAudience,sample:true}
];
