import {db} from '@/lib/db';
import {admin} from '@/lib/admin-auth';
import {prohibited} from '@/lib/moderation';
export const DOMAIN='els-egypt.info';
export const states=['Received','Under Review','Approved','Not Possible','Implemented'];
export const json=(v:unknown,status=200,headers:Record<string,string>={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store',...headers}});
export function clean(v:unknown,max=4000){if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('Please check the required fields.');return v.trim()}
export const cookie=(r:Request,key:string)=>(r.headers.get('cookie')||'').split('; ').find(v=>v.startsWith(key+'='))?.slice(key.length+1)||'';
export const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export const setCookie=(key:string,value:string,age:number)=>`${key}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
export async function session(r:Request,key:string){const token=cookie(r,key);if(!/^[a-f0-9]{64}$/.test(token))return '';const row=await db().prepare('SELECT actor FROM comm_sessions WHERE token=? AND expires>?').bind(await hash(token),Date.now()).first<{actor:string}>();return row?.actor||''}
export async function newSession(actor:string,days:number){await db().prepare('DELETE FROM comm_sessions WHERE expires<?').bind(Date.now()).run();const token=random();await db().prepare('INSERT INTO comm_sessions(token,actor,expires) VALUES(?,?,?)').bind(await hash(token),actor,Date.now()+days*86400000).run();return token}
export async function config(){const rows=await db().prepare('SELECT key,value FROM comm_config').all<{key:string;value:string}>();return Object.fromEntries(rows.results.map(x=>[x.key,x.value]))}
export async function moderate(text:string){const c=await config();if(prohibited(text,JSON.parse(c.blocked||'[]'),JSON.parse(c.allowed||'[]')))throw Error('Please rephrase your message without inappropriate language. Your draft has not been sent.')}
export type Person={email:string;name:string;role:string;class_name:string;classes:string;active:number};
export async function identity(r:Request){const email=await session(r,'hb_identity');const person=email?await db().prepare('SELECT * FROM comm_people WHERE email=? AND active=1').bind(email).first<Person>():null;const isAdmin=await admin(r);return {person,isAdmin,staff:isAdmin||person?.role==='staff',moderator:isAdmin||person?.role==='staff'||person?.role==='council',guest:await session(r,'hb_guest'),actor:person?.email||(isAdmin?'Bootstrap administrator':await session(r,'hb_guest'))}}
export type Context=Awaited<ReturnType<typeof identity>>;
export async function threadAccess(id:string,c:Context){const t=await db().prepare('SELECT * FROM comm_threads WHERE id=?').bind(id).first<any>();if(!t)throw Error('Conversation unavailable.');if(t.kind==='suggestion'){if(t.owner!==c.guest&&t.account!==c.person?.email&&!c.moderator)throw Error('Conversation unavailable.')}else{if(!c.person||(c.person.email!==t.owner&&c.person.email!==t.teacher))throw Error('Conversation unavailable.');const student=await db().prepare('SELECT * FROM comm_people WHERE email=? AND active=1').bind(t.owner).first<Person>();const teacher=await db().prepare('SELECT * FROM comm_people WHERE email=? AND active=1').bind(t.teacher).first<Person>();if(!student||!teacher||!['teacher','staff'].includes(teacher.role)||!JSON.parse(teacher.classes).includes(student.class_name))throw Error('Your class assignment has changed. Please contact the school.')}return t}
export class RateLimitError extends Error {}
export async function limit(key:string,max=40){const now=Date.now();await db().prepare('INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=CASE WHEN until<? THEN ? ELSE until END').bind('comm:'+key,now+60000,now,now,now+60000).run();const row=await db().prepare('SELECT count FROM attempts WHERE key=?').bind('comm:'+key).first<{count:number}>();if((row?.count||0)>max)throw new RateLimitError('Please wait a minute before trying again.')}
export async function addMessage(t:any,c:Context,body:string,file='',asStaff=false,requestId='',newStatus:string|null=null,replyTo=''){const sender=t.kind==='suggestion'?((t.owner===c.guest||t.account===c.person?.email)&&!asStaff?t.owner:c.actor):c.person?.email;const label=t.kind==='suggestion'?((t.owner===c.guest||t.account===c.person?.email)&&!asStaff?t.name:'High Board · '+(c.person?.name||'Administration')):c.person?.name;if(!sender)throw Error('Sign in first.');await db().batch([db().prepare('INSERT OR IGNORE INTO comm_messages(id,thread,sender,label,body,file,created,reply_to) VALUES(?,?,?,?,?,?,?,?)').bind(requestId?await hash(t.id+'|'+sender+'|'+requestId):crypto.randomUUID(),t.id,sender,label,body,file,Date.now(),replyTo),db().prepare('UPDATE comm_threads SET updated=?,status=COALESCE(?,status) WHERE id=?').bind(Date.now(),newStatus,t.id)]);}

export async function recordAudit(c:Context,action:string,target:string){await db().prepare('INSERT INTO comm_audit(id,actor,action,target,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),c.actor||'anonymous',action,target,Date.now()).run()}
