import {db} from '@/lib/db';
import {studentTripAccess,collectorClasses} from '@/lib/trips';
import type {Context,Person} from '@/lib/communications';
import {visible,type Item} from '@/lib/board';
export const contactRoles=['teacher','staff','administrator','council'];
export async function questionTrip(id:string){const row=await db().prepare("SELECT data FROM content WHERE id=? AND kind='event'").bind(id).first<{data:string}>();if(!row)throw Error('Trip unavailable.');const trip=JSON.parse(row.data) as Item;if(trip.category!=='Trip'||trip.sample||!['Published','Cancelled'].includes(trip.stage||'Published'))throw Error('Trip unavailable.');return trip}
export function canAssignContacts(trip:Item,c:Context){if(!c.person)return false;if(c.isAdmin||c.staff||c.person.role==='administrator')return true;const classes=collectorClasses(c);return c.person.role==='teacher'&&trip.owner===c.person.email&&classes!==null&&!trip.audience.is_global&&!trip.audience.target_grades.length&&trip.audience.target_classes.length>0&&trip.audience.target_classes.every(cl=>classes.includes(cl))}
export async function activeContacts(trip:string){return (await db().prepare("SELECT c.id,p.email,p.name,p.role FROM trip_contacts c JOIN comm_people p ON p.email=c.actor WHERE c.trip=? AND p.active=1 AND p.role IN ('teacher','staff','administrator','council') ORDER BY p.name,c.id").bind(trip).all<{id:string;email:string;name:string;role:string}>()).results}
export async function questionAccess(q:any,c:Context){const trip=await questionTrip(q.trip),contacts=await activeContacts(q.trip);const contact=contacts.find(p=>p.id===q.contact);const student=await db().prepare('SELECT * FROM comm_people WHERE email=? AND active=1').bind(q.student).first<Person>();if(!contact||!student||!studentTripAccess(trip,{...c,person:student}))throw Error('Question unavailable.');if(c.person?.email!==student.email&&c.person?.email!==contact.email)throw Error('Question unavailable.');return {trip,contact,student}}
