import {db,files} from '@/lib/db';
import {identity,threadAccess,json,clean,limit,moderate} from '@/lib/communications';
import {validateFile} from '@/lib/file-validation';
export const dynamic='force-dynamic';
const CHUNK=8*1024*1024,MAX=500*1024*1024,DAY=2*1024*1024*1024;
export async function POST(r:Request){try{if(r.headers.get('origin')!==new URL(r.url).origin)return json({error:'Request not allowed'},403);const c=await identity(r);if(!c.person)return json({error:'School sign-in required.'},401);const u=new URL(r.url),action=u.searchParams.get('action');const d=db();
if(action==='begin'){await limit('media-start:'+c.person.email,10);const raw=await r.text();if(raw.length>2000)throw Error('Request too large.');const b=JSON.parse(raw),t=await threadAccess(clean(b.thread),c);if(t.kind!=='chat')throw Error('Files belong in teacher conversations.');const size=Number(b.size);if(!Number.isSafeInteger(size)||size<=20*1024*1024||size>MAX)throw Error('Large media must be between 20 MB and 500 MB.');const name=clean(b.name,120).replace(/[^\p{L}\p{N} ._()-]/gu,'_');await moderate(name);if(!/\.(mp4|mov|webm|m4a|mp3|ogg|oga|wav)$/i.test(name))throw Error('Large uploads support video and audio only.');const mime=String(b.mime||'');if(!/^(video|audio)\//.test(mime))throw Error('Choose a video or audio file.');const expired=(await d.prepare('SELECT id,object_key,upload_id FROM media_uploads WHERE actor=? AND created<?').bind(c.person.email,Date.now()-86400000).all<any>()).results;for(const old of expired){await files().resumeMultipartUpload(old.object_key,old.upload_id).abort();await d.batch([d.prepare('DELETE FROM media_parts WHERE upload=?').bind(old.id),d.prepare('DELETE FROM media_uploads WHERE id=?').bind(old.id)])}const usage=await d.prepare('SELECT SUM(size) total FROM comm_files WHERE actor=? AND created>?').bind(c.person.email,Date.now()-86400000).first<{total:number}>();const active=await d.prepare('SELECT COUNT(*) n,SUM(size) total FROM media_uploads WHERE actor=?').bind(c.person.email).first<{n:number;total:number}>();if((active?.n||0)>=3)throw Error('Finish or cancel your other uploads first.');if((usage?.total||0)+(active?.total||0)+size>DAY)throw Error('The daily 2 GB upload allowance has been reached.');const id=crypto.randomUUID(),key='messages/'+id,upload=await files().createMultipartUpload(key,{httpMetadata:{contentType:mime}});try{await d.prepare('INSERT INTO media_uploads(id,actor,thread,object_key,upload_id,name,mime,size,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,c.person.email,t.id,key,upload.uploadId,name,mime,size,Date.now()).run()}catch(e){await upload.abort();throw e}return json({id,chunkSize:CHUNK});}
const id=u.searchParams.get('id')||'',row=await d.prepare('SELECT * FROM media_uploads WHERE id=? AND actor=?').bind(id,c.person.email).first<any>();if(!row)throw Error('Upload unavailable.');await threadAccess(row.thread,c);const upload=files().resumeMultipartUpload(row.object_key,row.upload_id);
async function remove(){await d.batch([d.prepare('DELETE FROM media_parts WHERE upload=?').bind(id),d.prepare('DELETE FROM media_uploads WHERE id=?').bind(id)])}
if(action==='abort'||row.created<Date.now()-86400000){await upload.abort();await remove();return json({ok:true})}
if(action==='part'){await limit('media-part:'+c.person.email,120);const part=Number(u.searchParams.get('part')),count=Math.ceil(row.size/CHUNK);if(!Number.isInteger(part)||part<1||part>count)throw Error('Invalid upload part.');const expected=part===count?row.size-(part-1)*CHUNK:CHUNK;const reader=r.body?.getReader();if(!reader)throw Error('Missing file part.');const chunks:Uint8Array[]=[];let size=0;for(;;){const v=await reader.read();if(v.done)break;size+=v.value.length;if(size>expected){await reader.cancel();throw Error('File part too large.')}chunks.push(v.value)}if(size!==expected)throw Error('Incomplete file part. Please retry.');const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length}if(part===1){if(!/\.(mp4|mov|webm|m4a|mp3|ogg|oga|wav)$/i.test(row.name))throw Error('Unsupported file.');const mime=validateFile(bytes,row.name,row.mime);if(!/^(video|audio)\//.test(mime))throw Error('Unsupported media.');await d.prepare('UPDATE media_uploads SET mime=? WHERE id=?').bind(mime,id).run();}const result=await upload.uploadPart(part,bytes);await d.prepare('INSERT INTO media_parts(upload,part,etag) VALUES(?,?,?) ON CONFLICT(upload,part) DO UPDATE SET etag=excluded.etag').bind(id,part,result.etag).run();return json({ok:true});}
if(action==='complete'){const parts=(await d.prepare('SELECT part,etag FROM media_parts WHERE upload=? ORDER BY part').bind(id).all<{part:number;etag:string}>()).results;if(parts.length!==Math.ceil(row.size/CHUNK)||parts.some((p,i)=>p.part!==i+1))throw Error('Some parts are missing. Please retry the upload.');await upload.complete(parts.map(p=>({partNumber:p.part,etag:p.etag})));const object=await files().head(row.object_key);if(!object||object.size!==row.size){await files().delete(row.object_key);throw Error('Upload size check failed.');}await d.prepare('INSERT OR IGNORE INTO comm_files(id,thread,actor,name,mime,size,object_key,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,row.thread,row.actor,row.name,row.mime,row.size,row.object_key,Date.now()).run();await remove();return json({id,name:row.name,mime:row.mime,size:row.size});}
throw Error('Unknown upload action.');}catch(e){return json({error:e instanceof Error?e.message:'Upload failed. Please retry.'},400)}}
