import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const content = sqliteTable('content',{id:text('id').primaryKey(),kind:text('kind').notNull(),data:text('data').notNull()});
export const responses = sqliteTable('responses',{item:text('item').notNull(),student:text('student').notNull(),value:text('value').notNull(),created:integer('created').notNull() },t=>[primaryKey({columns:[t.item,t.student]})]);
export const attempts = sqliteTable('attempts',{key:text('key').primaryKey(),count:integer('count').notNull(),until:integer('until').notNull()});
export const commPeople = sqliteTable('comm_people',{email:text('email').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),className:text('class_name').notNull().default(''),classes:text('classes').notNull().default('[]'),active:integer('active').notNull().default(1)});
export const commSessions = sqliteTable('comm_sessions',{token:text('token').primaryKey(),actor:text('actor').notNull(),expires:integer('expires').notNull()},t=>[index('comm_session_expiry').on(t.expires)]);
export const commThreads = sqliteTable('comm_threads',{id:text('id').primaryKey(),kind:text('kind').notNull(),owner:text('owner').notNull(),name:text('name').notNull(),account:text('account').notNull().default(''),category:text('category').notNull().default('General'),assignee:text('assignee').notNull().default(''),teacher:text('teacher').notNull().default(''),title:text('title').notNull(),status:text('status').notNull().default('Received'),updated:integer('updated').notNull()},t=>[index('comm_thread_owner').on(t.owner),index('comm_thread_teacher').on(t.teacher)]);
export const commMessages = sqliteTable('comm_messages',{replyTo:text('reply_to').notNull().default(''),id:text('id').primaryKey(),thread:text('thread').notNull(),sender:text('sender').notNull(),label:text('label').notNull(),body:text('body').notNull(),file:text('file').notNull().default(''),created:integer('created').notNull()},t=>[index('comm_message_thread_created').on(t.thread,t.created),index('comm_message_file').on(t.file)]);
export const commFiles = sqliteTable('comm_files',{id:text('id').primaryKey(),thread:text('thread').notNull(),actor:text('actor').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),objectKey:text('object_key').notNull(),created:integer('created').notNull()});
export const commReads = sqliteTable('comm_reads',{thread:text('thread').notNull(),actor:text('actor').notNull(),seen:integer('seen').notNull()},t=>[primaryKey({columns:[t.thread,t.actor]})]);
export const commConfig = sqliteTable('comm_config',{key:text('key').primaryKey(),value:text('value').notNull()});
export const commReports = sqliteTable('comm_reports',{id:text('id').primaryKey(),message:text('message').notNull(),actor:text('actor').notNull(),reason:text('reason').notNull(),created:integer('created').notNull(),resolved:integer('resolved').notNull().default(0)});

export const recovery = sqliteTable('comm_recovery',{token:text('token').primaryKey(),owner:text('owner').notNull(),created:integer('created').notNull()});
export const audit = sqliteTable('comm_audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),created:integer('created').notNull()});
export const notes = sqliteTable('comm_notes',{id:text('id').primaryKey(),thread:text('thread').notNull(),author:text('author').notNull(),body:text('body').notNull(),created:integer('created').notNull()});

export const workspaceSchedule = sqliteTable('workspace_schedule',{id:text('id').primaryKey(),actor:text('actor').notNull(),data:text('data').notNull()});
export const mediaUploads = sqliteTable('media_uploads',{id:text('id').primaryKey(),actor:text('actor').notNull(),thread:text('thread').notNull(),objectKey:text('object_key').notNull(),uploadId:text('upload_id').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),created:integer('created').notNull()});
export const mediaParts = sqliteTable('media_parts',{upload:text('upload').notNull(),part:integer('part').notNull(),etag:text('etag').notNull()},t=>[primaryKey({columns:[t.upload,t.part]})]);
export const tripInterest = sqliteTable('trip_interest',{trip:text('trip').notNull(),actor:text('actor').notNull(),choice:text('choice').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.trip,t.actor]}),index('trip_interest_actor').on(t.actor)]);
