import {db} from '@/lib/db';
import {identity,json,clean,limit,moderate,recordAudit} from '@/lib/communications';
import {studentTripAccess} from '@/lib/trips';
import {questionTrip,canAssignContacts,activeContacts,questionAccess,contactRoles} from '@/lib/trip-questions';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{
 const c=await identity(r);if(!c.person)return json({error:'School sign-in required.'},401);const d=db(),params=new URL(r.url).searchParams;
 if(params.get('inbox')==='1'){const rows=(await d.prepare("SELECT q.*,p.email,p.name,p.role,p.class_name,p.classes,p.active,i.data trip_data FROM trip_questions q JOIN trip_contacts c ON c.id=q.contact JOIN comm_people recipient ON recipient.email=c.actor JOIN comm_people p ON p.email=q.student JOIN content i ON i.id=q.trip AND i.kind='event' WHERE c.actor=? AND recipient.active=1 AND recipient.role IN ('teacher','staff','administrator','council') AND p.active=1 ORDER BY q.created DESC LIMIT 200").bind(c.person.email).all<any>()).results;const questions=rows.filter(q=>{const trip=JSON.parse(q.trip_data);return trip.category==='Trip'&&!trip.sample&&studentTripAccess(trip,{...c,person:q})}).map(q=>({id:q.id,trip:JSON.parse(q.trip_data).title,name:q.name,class_name:q.class_name,body:q.body,answer:q.answer,created:q.created,answered:q.answered}));return json({questions})}
 const trip=await questionTrip(clean(params.get('trip'),100));const manager=canAssignContacts(trip,c);if(!manager&&!studentTripAccess(trip,c))return json({error:'Trip unavailable for your account.'},403);const contacts=await activeContacts(trip.id);
 if(params.get('manage')==='1'){if(!manager)return json({error:'Only staff or the assigned trip organiser can change contacts.'},403);const candidates=(await d.prepare("SELECT email,name,role FROM comm_people WHERE active=1 AND role IN ('teacher','staff','administrator','council') ORDER BY name").all<any>()).results;return json({contacts,candidates})}
 const rows=(await d.prepare('SELECT id,contact,body,answer,created,answered FROM trip_questions WHERE trip=? AND student=? ORDER BY created DESC LIMIT 50').bind(trip.id,c.person.email).all<any>()).results;
 return json({contacts:contacts.map(({email,...p})=>p),questions:rows.filter(q=>contacts.some(p=>p.id===q.contact)),canAsk:studentTripAccess(trip,c)&&trip.stage!=='Cancelled'&&!!trip.start&&Date.parse(trip.start)>Date.now()});
 }catch{return json({error:'Unable to load trip questions.'},400)}}
export async function POST(r:Request){try{
 if(r.headers.get('origin')!==new URL(r.url).origin)return json({error:'Request not allowed.'},403);const c=await identity(r);if(!c.person)return json({error:'School sign-in required.'},401);const raw=await r.text();if(raw.length>5000)return json({error:'Request too large.'},413);const b=JSON.parse(raw),d=db();await limit('trip-questions:'+c.person.email,20);
 if(b.action==='assign'){const trip=await questionTrip(clean(b.trip,100));if(!canAssignContacts(trip,c))return json({error:'Only staff or the assigned trip organiser can change contacts.'},403);if(!Array.isArray(b.contacts)||b.contacts.length>4||b.contacts.some((x:unknown)=>typeof x!=='string'))throw Error('Choose up to four trip contacts.');const emails=[...new Set<string>(b.contacts)];for(const email of emails){const p=await d.prepare('SELECT role FROM comm_people WHERE email=? AND active=1').bind(email).first<{role:string}>();if(!p||!contactRoles.includes(p.role))throw Error('Choose an active teacher, staff member or High Board helper.');}const saved=(await d.prepare('SELECT id,actor FROM trip_contacts WHERE trip=?').bind(trip.id).all<{id:string;actor:string}>()).results;const removals=saved.filter(p=>!emails.includes(p.actor));const additions=emails.filter(e=>!saved.some(p=>p.actor===e));const statements=[...removals.map(p=>d.prepare('DELETE FROM trip_contacts WHERE id=?').bind(p.id)),...additions.map(e=>d.prepare('INSERT OR IGNORE INTO trip_contacts(id,trip,actor) VALUES(?,?,?)').bind(crypto.randomUUID(),trip.id,e))];if(statements.length)await d.batch(statements);await recordAudit(c,'Trip question contacts changed',trip.id);return json({ok:true})}
 if(b.action==='ask'){const trip=await questionTrip(clean(b.trip,100));if(!studentTripAccess(trip,c))return json({error:'A verified student in the trip audience is required.'},403);if(trip.stage==='Cancelled'||!trip.start||Date.parse(trip.start)<=Date.now())return json({error:'Questions have closed for this trip.'},409);const contact=(await activeContacts(trip.id)).find(p=>p.id===b.contact);if(!contact||contact.email===c.person.email)throw Error('Choose an available trip contact.');const body=clean(b.body,1000);await moderate(body);const id=crypto.randomUUID();await d.prepare('INSERT INTO trip_questions(id,trip,contact,student,body,created) VALUES(?,?,?,?,?,?)').bind(id,trip.id,contact.id,c.person.email,body,Date.now()).run();return json({ok:true,id})}
 if(b.action==='reply'){const q=await d.prepare('SELECT * FROM trip_questions WHERE id=?').bind(clean(b.id,100)).first<any>();if(!q)throw Error('Question unavailable.');const a=await questionAccess(q,c);if(a.contact.email!==c.person.email)return json({error:'Only the selected contact can reply.'},403);const answer=clean(b.answer,1000);await moderate(answer);await d.prepare('UPDATE trip_questions SET answer=?,answered=? WHERE id=?').bind(answer,Date.now(),q.id).run();return json({ok:true})}
 throw Error('Unknown action.');
 }catch(e){return json({error:e instanceof Error?e.message:'Unable to save.'},400)}}
