import {db} from '@/lib/db';
import {identity,json,clean,moderate,limit,recordAudit} from '@/lib/communications';
import {visible} from '@/lib/board';
export const dynamic='force-dynamic';
function assigned(c:any){return c.person?JSON.parse(c.person.classes):[]}
export async function GET(r:Request){try{const c=await identity(r);if(!c.person)return json({person:null});const rows=(await db().prepare("SELECT data FROM content WHERE kind IN ('announcement','event','poll')").all<{data:string}>()).results.map(x=>JSON.parse(x.data));const cls=c.person.class_name;const classes=assigned(c);const canManage=c.isAdmin||c.moderator||c.person.role==='teacher';const items=rows.filter(i=>c.isAdmin||i.owner===c.person!.email||c.staff&&i.stage==='Pending approval'||(['Published','Cancelled'].includes(i.stage||'Published')&&(cls?visible(i.audience,Number(cls.slice(0,-1)),cls):classes.some((cl:string)=>visible(i.audience,Number(cl.slice(0,-1)),cl)))));const schedule=(await db().prepare('SELECT id,data FROM workspace_schedule WHERE actor=?').bind(c.person.email).all<{id:string;data:string}>()).results.map(x=>({id:x.id,...JSON.parse(x.data)}));return json({person:{name:c.person.name,role:c.person.role,class_name:cls,classes},canManage,items:items.map(({owner,...i}:any)=>({...i,mine:owner===c.person!.email})),schedule});}catch{return json({error:'Unable to load your workspace.'},400)}}
export async function POST(r:Request){try{if(r.headers.get('origin')!==new URL(r.url).origin)return json({error:'Request not allowed'},403);const text=await r.text();if(text.length>16000)return json({error:'Request too large'},413);const b=JSON.parse(text),c=await identity(r);if(!c.person)return json({error:'School sign-in required.'},401);await limit('workspace:'+c.person.email);const d=db(),teacher=c.person.role==='teacher',manager=teacher||c.moderator||c.isAdmin;
if(b.action==='schedule'){if(!['teacher','staff','administrator'].includes(c.person.role))throw Error('Teacher access required.');const day=Number(b.day),start=String(b.start||''),end=String(b.end||''),className=String(b.class_name||'');if(!Number.isInteger(day)||day<0||day>6||!/^([01]\d|2[0-3]):[0-5]\d$/.test(start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(end)||end<=start)throw Error('Check the day and session times.');if(className&&!assigned(c).includes(className)&&!c.isAdmin)throw Error('Choose an assigned class.');const saved=(await d.prepare('SELECT data FROM workspace_schedule WHERE actor=?').bind(c.person.email).all<{data:string}>()).results.map(x=>JSON.parse(x.data));if(saved.some(x=>x.day===day&&start<x.end&&end>x.start))throw Error('This overlaps another session or break.');const data={day,start,end,class_name:className,title:clean(b.title,120),room:String(b.room||'').slice(0,80),kind:b.kind==='Break'?'Break':'Session'};await moderate(data.title);await d.prepare('INSERT INTO workspace_schedule(id,actor,data) VALUES(?,?,?)').bind(crypto.randomUUID(),c.person.email,JSON.stringify(data)).run();return json({ok:true})}
if(b.action==='removeSchedule'){await d.prepare('DELETE FROM workspace_schedule WHERE id=? AND actor=?').bind(clean(b.id),c.person.email).run();return json({ok:true})}
if(!manager)throw Error('Publishing access required.');
if(b.action==='release'){const row=await d.prepare('SELECT data FROM content WHERE id=?').bind(clean(b.id)).first<{data:string}>();if(!row)throw Error('Content unavailable.');const i=JSON.parse(row.data);if(!['Draft','Pending approval'].includes(i.stage))throw Error('This post is already released.');if(!c.staff&&i.owner!==c.person.email)throw Error('You can only submit your own draft.');if(teacher&&(i.audience.is_global||i.audience.target_grades.length||i.audience.target_classes.some((cl:string)=>!assigned(c).includes(cl))))throw Error('Your class assignments have changed.');if(i.kind==='poll'&&!(Date.parse(i.end)>Date.now()))throw Error('The voting deadline has passed. Create a new poll.');i.stage=c.person.role==='council'?'Pending approval':'Published';await d.prepare('UPDATE content SET data=? WHERE id=?').bind(JSON.stringify(i),b.id).run();await recordAudit(c,'Workspace '+i.stage,i.id);return json({ok:true,stage:i.stage})}
if(b.action==='archive'){const row=await d.prepare('SELECT data FROM content WHERE id=?').bind(clean(b.id)).first<{data:string}>();if(!row)throw Error('Content unavailable.');const i=JSON.parse(row.data);if(!c.isAdmin&&i.owner!==c.person.email)throw Error('You can only archive your own posts.');i.stage='Archived';await d.prepare('UPDATE content SET data=? WHERE id=?').bind(JSON.stringify(i),b.id).run();await recordAudit(c,'Workspace content archived',b.id);return json({ok:true})}
if(b.action!=='publish')throw Error('Unknown action.');const classes=Array.isArray(b.classes)?[...new Set(b.classes)]:[];const grades=Array.isArray(b.grades)?[...new Set(b.grades)]:[];if(classes.some((x:any)=>typeof x!=='string'||!/^([1-9]|1[0-2])[A-Z]$/.test(x))||grades.some((x:any)=>!Number.isInteger(x)||x<1||x>12))throw Error('Choose a valid audience.');if(teacher&&(b.global||grades.length||!classes.length||classes.some(x=>!assigned(c).includes(x))))throw Error('Teachers can publish only to their assigned classes.');if(!b.global&&!classes.length&&!grades.length)throw Error('Choose an audience.');const kind=String(b.kind);if(!['announcement','event','poll'].includes(kind))throw Error('Choose a content type.');if(kind==='poll'&&teacher)throw Error('School polls are managed by High Board.');const title=clean(b.title,160),description=clean(b.description,2000);await moderate(title+' '+description);const stage=b.stage==='Draft'?'Draft':c.person.role==='council'?'Pending approval':'Published';const i:any={id:crypto.randomUUID(),kind,title,description,owner:c.person.email,author:c.person.name,created:Date.now(),stage,audience:{is_global:!!b.global,target_grades:grades,target_classes:classes,excluded_classes:[]}};
if(kind==='announcement'){i.effective=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());}
if(kind==='event'){i.category=b.category==='Trip'?'Trip':'Class Event';i.start=clean(b.start);i.end=clean(b.end);if(!Number.isFinite(Date.parse(i.start))||!Number.isFinite(Date.parse(i.end))||Date.parse(i.end)<=Date.parse(i.start))throw Error('End must be after start.');i.room=String(b.room||'').slice(0,100);}
if(kind==='poll'){i.options=String(b.options||'').split('\n').map(s=>s.trim()).filter(Boolean);if(i.options.length<2||i.options.length>8||i.options.some((s:string)=>s.length>100))throw Error('Enter 2–8 choices, one per line.');await moderate(i.options.join(' '));i.end=clean(b.end);if(!(Date.parse(i.end)>Date.now()))throw Error('Choose a future closing date.');i.verified=true;i.multi=false;}
await d.prepare('INSERT INTO content(id,kind,data) VALUES(?,?,?)').bind(i.id,kind,JSON.stringify(i)).run();await recordAudit(c,'Workspace '+stage,i.id);return json({ok:true,stage});}catch(e){return json({error:e instanceof Error?e.message:'Unable to save.'},400)}}
